### PR TITLE
Material system refactor 2

### PR DESCRIPTION
**Pull request by guycalledfrank**
- fixed a few bugs from previous PR.

- phongmaterial.getUniform("phongmaterial property name", value to set)
returns you a "uniform object", that looks like this: {name:uniformName, value:uniformValue} or an 
array: [uniformObject, uniformObject].
- material.setParameter accepts such objects/arrays.

can be used to simplify usage of https://github.com/playcanvas/engine/pull/318
So instead of writing:
```javascript
            var tform = new pc.Vec4(0.11, 1, this.offset, 0);
            obj.setParameter("texture_diffuseMapTransform", tform.data);
```
You can write:
```javascript
            var overrideOffset = obj.material.getUniform("diffuseMapOffset", new pc.Vec2(this.offset, 0));
            obj.setParameter(overrideOffset);
```
or Instead of
```javascript
obj.setParameter("material_diffuse", color.data);
```
you can do
```javascript
            var override = obj.material.getUniform("diffuse", color);
            obj.setParameter(override);
```

### CODE REVIEW

**Comment by vkalpias** [comment]
Seems kindof confusing to me that in order to set a value I call getUniform

**Comment by guycalledfrank** [comment]
getUniform is the way to set uniform overrides on meshInstances.
To change per-material parameters, you do it as usual.

**Comment by vkalpias** [comment]
Shouldn't it be called setUniform then?

**Comment by guycalledfrank** [comment]
No. Because it gets uniform. It doesn't change anything. It returns you a structure with uniform name + value (possibly processed, like shininess rescale from 0-100 to 0-1 etc).

**Pull request merged**
