### PR TITLE
Run scenes with corrupted data

### PR DESCRIPTION
**Pull request by yaustar**
Related to https://github.com/playcanvas/editor/issues/758

We have existing scenes that could be corrupted by this issue and at the moment, they fail to launch leaving users confused.

This PR allows these scenes to launch with a warning

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

Tested against:
https://playcanvas.com/project/923035/overview/double-graphnode-parent

Current
image

With this PR
image

### CODE REVIEW

**Review by mvaligursky — APPROVED** [review]

**Comment by slimbuck** [comment]
What can users do when they see this message? Can they fix their scenes?

**Comment by yaustar** [comment]
@slimbuck Currently, the only way they can fix the issue is to do one of the methods here (the version control method is the easiest) https://forum.playcanvas.com/t/cannot-find-child-entity-of-parent-root-editor-error-cant-delete-entities/23048

**Comment by slimbuck** [comment]
We should really be fixing these automatically in the editor at load time since we now know what the issue is.

**Comment by yaustar** [comment]
Should it be like the pop up that we had before around the template issue so that it's a user action to fix?

**Comment by slimbuck** [comment]
> Should it be like the pop up
I think we can just fix it at load time and perhaps show a message saying we have. The reason we don't need user input is we won't be modifying the scene in any way, just getting rid of invalid entities (right?).

**Comment by yaustar** [comment]
In theory, yes. From a user perspective, I would prefer to have the opt-in so I can have the assurance of making a checkpoint, or being able to examine the scene before making changes

**Comment by slimbuck** [comment]
I thought these problem scenes don't load correctly in the editor?

**Comment by yaustar** [comment]
They do but will have Entities that you can't delete (eg https://playcanvas.com/project/1011865/overview/example-broken-project try deleting New Entity). However, you can still edit, add new entities etc.

**Pull request merged**
