### PR TITLE
PlayCanvas Discord

### PR DESCRIPTION
**Pull request by SHADOWELITE7**
Another way to bring others to the discord server

### CODE REVIEW

**Comment by willeastcott** [comment]
Thanks! 👍

**Comment by SHADOWELITE7** [comment]
your welcome

**Comment by yushimatenjin** [comment]
has expired ?

**Comment by yaustar** [comment]
Here's a permanent link: https://discord.gg/tjJWEHT

**Comment by charlie-george-1989** [comment]
@yaustar that link won't work for me.

**Comment by yaustar** [comment]
https://discord.gg/RSaMRzg

**Comment by charlie-george-1989** [comment]
Okay thanks mate!

**Comment by charlie-george-1989** [comment]
Thanks dude!
________________________________

**Pull request merged**
