### PR TITLE
[FIX] Check _flipFaces on camera not camera component

### PR DESCRIPTION
**Pull request by slimbuck**
Error introduced in #3346

### CODE REVIEW

**Comment by yaustar** [comment]
Should we rename `camera` to `cameraComponent`?

**Review by yaustar — APPROVED** [review]
LGTM. Comment previously provided 'Should we rename `camera` to `cameraComponent`'

**Comment by slimbuck** [comment]
> Should we rename `camera` to `cameraComponent`?

Maybe some other time :)

**Comment by yaustar** [comment]
> > Should we rename `camera` to `cameraComponent`?
> 
> Maybe some other time :)

Would we hit the same issue next time though? It's only because I double check potential tutorial projects that may be affected by render textures that we found this?

**Comment by willeastcott** [comment]
We should add that project to the test plan. 😄

**Comment by slimbuck** [comment]
> We should add that project to the test plan. 😄

Done :)

**Pull request merged**
