### PR TITLE
Added another check condition if it's safari on iOS.

### PR DESCRIPTION
**Pull request by figo2264**
Fixes #

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### Description
On the relatively latest safari on iOS, it keeps trying to load image via _loadImageBitmapFromBlob method.

```javascript
        if (hasContents) {
            // ImageBitmap interface can load iage
            if (this.device.supportsImageBitmap) {
                this._loadImageBitmapFromBlob(new Blob([asset.file.contents]), callback);
                return;
            }
            url = {
                load: URL.createObjectURL(new Blob([asset.file.contents])),
                original: url.original
            };
        }
``` 

According to the code from webgl-graphics-device, it shouldn't be loaded via the method.
Somehow, checking 'Safari' isn't working as expected.

Added additional check condition when it is ios device.

Affected files are
- platform.js
- webgl-graphics-device.js

SafariOnIosImageBitmap

### CODE REVIEW

**Comment by slimbuck** [comment]
Hi @figo2264 ,

Thanks so much for this PR! I was looking at the same issue for another user and have submitted [this PR](https://github.com/playcanvas/engine/pull/5383) to address it. I added logic to detect more generally which browser is currently running. Are you ok for me to close this PR in favour of the other?

Thanks!

**Comment by figo2264** [comment]
@slimbuck Sure. You can close my PR since it's duplicated.
FYI, my issue was happening only in Safari browser on iPhone. It was working fine with iPad and Mac environment.

**Comment by slimbuck** [comment]
Thanks @figo2264.

I believe the ipad has the option "request desktop site" enabled by default. So depending on whether that is enabled or not the old way of detecting safari (`window.safari`) might have been working for you.

Will you be able to test [it works](https://github.com/playcanvas/engine/pull/5383) once it's merged?

**Comment by figo2264** [comment]
@slimbuck Don't worry. I've temporarily fixed my issue with my code and now it works fine. 
I will test once after your PR is merged..

**Comment by slimbuck** [comment]
Closing in favour of https://github.com/playcanvas/engine/pull/5383

**Pull request closed without merging**
