### PR TITLE
Attempt to fix autocomplete

### PR DESCRIPTION
**Pull request by vkalpias**

### CODE REVIEW

**Review by slimbuck — APPROVED** [review]

**Review by willeastcott — APPROVED** [review]

**Comment by willeastcott** [comment]
Note to @TheJonRobinson - your PR unfortunately broke the code editor's autocomplete. We're partially backing it out for now.

**Comment by willeastcott** [comment]
We really need to switch to a system whereby the autocomplete is derived from the `playcanvad.d.ts` file. This will avoid these problems in future.

**Comment by TheJonRobinson** [comment]
Oh wow - sorry, did I do something wrong and/or know what to look out for in future?

**Comment by slimbuck** [comment]
Hey @TheJonRobinson - no not at all. We just have a slightly flakey autocomplete pipeline which needs updating. Sorry about this!

**Pull request merged**
