### PR TITLE
Add support for ES6 script classes

### LINKED ISSUE #1907: Support ES6 script classes
JavaScript introduced the [`class`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) keyword in back in 2015 with the release of ES6. Many top JS libraries, such as `React`, have made classes an indispensable language feature when they introduced support for extending base classes, e.g. `extends React.Component` (instead of using ES5-style `React.createClass()`). In fact, `React` removed support for `React.createClass()` entirely in 2017 in favor of classes. Today, classes are a fundamental part of JavaScript, and many new JavaScript devs don't remember a time before classes.

We don't propose PlayCanvas drop support for `pc.createScript()` but introduce the option of writing ES6 script classes (i.e. `extends pc.ScriptType`). We're a strong believer in letting devs choose the best tool for their job. Example:

```javascript
class CameraController extends pc.ScriptType {

    initialize() {
        // initialize code called once per entity 
    }

    update(dt) {
        // update code called every frame
    }
}
```

Almost all browsers natively support classes (only exception being IE). And if a dev wishes to have both classes and IE-support, then ES6 code (just like TypeScript) can easily be transpiled to vanilla ES5 - making it an non-issue.

image

### PR DESCRIPTION
**Pull request by aidinabedi**
Fixes #1907 (also #1889 and #1887).

PR consists of the following significant changes:
- Separate all code related to `pc.ScriptType` and `pc.ScriptAttributes` from `pc.createScript()` (and move into own files `script-type.js` and `script-attributes.js`).
- Fix `pc.ScriptType` and `pc.ScriptAttributes` to work as regular standalone public classes (instead of imaginary types existing only in the docs). Also making `pc.ScriptType` possible to extend in ES6.
- Add `pc.registerScript()` to register ES6 script classes (which doesn't need `pc.createScript()`). Includes full documentation and example.
- Update `pc.createScript()` to use new `pc.registerScript()`, `pc.ScriptType`, and `pc.ScriptAttributes` and keep backward-compatibility. 
- Fix JSDoc and TS delcarations that should reference the `pc.ScriptType` class itself, instead of the instance (see issues #1889 and #1887). Requires jsdoc template fix: https://github.com/playcanvas/playcanvas-jsdoc-template/pull/8 (make sure template package is updated with fix).
----

Using the PR devs can now choose between either regular ES5-style or ES6-class scripts:

### ES5 example:
```javascript
var CameraController = pc.createScript('CameraController');

CameraController.attributes.add('myAttrib', { type: 'boolean', default: false });

CameraController.prototype.initialize = function() {
    // initialize code called once per entity 
};

CameraController.prototype.update = function(dt) {
    // update code called every frame
};
```

### ES6 example:
```javascript
class CameraController extends pc.ScriptType {

    initialize() {
        // initialize code called once per entity 
    }

    update(dt) {
        // update code called every frame
    }
}

CameraController.attributes.add('attribute', { type: 'boolean', default: false });

pc.registerScript(CameraController);
```
----

All changes have been tested using a [public PlayCanvas project](https://playcanvas.com/project/668763/overview/es6-script-tests) (simply run it with and without the PR):

### With PR:
image

### Without PR:
image

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
This looks pretty cool. @vkalpias and @Maksims - any objections before I merge?

**Comment by Maksims** [comment]
**I'm good**, only have few things to be clarified before merging:

1. From first glance I don't see any behavioural changes, and to keep this PR simple its good. If I'm wrong, please clarify.
2. This PR needs to be throughout tested on existing projects Editor based as well as engline-only.
3. With introduction of ES6 Classes path, we should update Editor WebWorker for parsing attributes. It should still be **optional** path, so not to drop support of IE11 users of Editor.
4. If developer decides to use ES6 Classes path in Editor, this makes Editor not usable in Internet Explorer 11. Glance at analytics will probably indicate very tiny fraction of users who it potentially affects.
5. This slightly affects performance, due to extra prototype level on script objects. But perhaps this would be insignificant to even measure the impact.

**Comment by willeastcott** [comment]
@Maksims 

1. Yeah, I think that's correct.
2. Yep, we'll run the full test plan before we deploy this.
3. The Editor doesn't support IE11 since last October or something like that (when we switched to laying out everything with flexbox).
4. See 3.
5. I suspect you're right that the performance implications are negligible.

**Comment by Glidias** [comment]
Some things to take note of though:

1. Is `Class<pc.ScriptType>` a proper type in TypeScript? I tried out that type signature in the latest typescript on playground and it yields an error. Typescript definitions might cause an error with this as well. This won't solve the problem i have with regards to type hinting/intellisense.. 

2. If using minifiers (particularly along build tool chains such as webpack), there can be cases where the `__getFuncName()` method might end up referencing mangled class names typically by default. (THe same cases may occur withconstructor.name cases...) This can/may be circumvented with webpack minifier options to preserve function names, but i'm not sure of the edge cases where even using such options  where even the option to preserve function names might still not work.

**Comment by aidinabedi** [comment]
@Glidias Thank you for the comment.

1. `Class<T>` is a [tsd-jsdoc convention](https://github.com/englercj/tsd-jsdoc#extended-support-for-ts-features) that is automatically converted to `typeof T`. So if you [generate the TypeScript definitions](https://github.com/playcanvas/engine#typescript-bindings) you will see that the actual TypeScript code results in `typeof T` instead of `Class<T>`. Similarity the [API reference documentation](https://developer.playcanvas.com/en/api/) will also automatically be converted to `typeof T` when the new version is officially released. 

2. Correct, the `__getFuncName()` will end up returning mangled class names, if minifed. That is why [`pc.registerScript()` has an optional `name` parameter](https://github.com/playcanvas/engine/blob/master/src/script/script.js#L81) which will let you specific the exact class name for precisely such cases. Would probably be good to add that in the documentation (in a separate PR). Your more than welcome to contribute! :)

Agreed. Ideally, there would be a `pc.scriptType` decorator which would take care of calling `registerScript`. That is something I would love to add later as a built-in feature, given the opportunity.

**Comment by Glidias** [comment]
Decorators though would require custom babel settings and such since it's an experimental feature , so I don't think it can be a built in feature even though technically the method could still be included as a module for optional use.

**Comment by Glidias** [comment]
1. Yes, it does export out to `typeof T`. I tested it out and looks like the prototype implementation methods now provide typehinting, but the problem though, is now you lose typehinting/type-checking for .attributes property on the typeof (=>Class) itself. Shouldn't `readonly attributes` be `static readonly attributes`? 

```
ES5Script.prototype.initialize = function() {
    this.fire('initialize');
    alert(this.attributes);
};
```
`attributes` is undefined. This goes to show that `attributes` should had been a static property all this while.

**Comment by aidinabedi** [comment]
@Glidias [I've fixed the issue with `attributes` not being recognized as static](https://github.com/playcanvas/engine/issues/1946). It was simply due to an old incorrect naming syntax (`pc.ScriptType#attributes` -> `pc.ScriptType.attributes`).

**Pull request merged**
