### PR TITLE
Update vec2.js

### PR DESCRIPTION
**Pull request by olkotov**
Documentation copypasta fix

Fixes #

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
I think this problem is duplicated in vec3.js. Can you fix that too please?

**Comment by willeastcott** [comment]
Also, don't forget to fill out the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform). 😄

**Comment by willeastcott** [comment]
Fantastic - thank you! 🎉

**Review by willeastcott — APPROVED** [review]

**Comment by olkotov** [comment]
https://developer.playcanvas.com/en/api/pc.GraphNode.html#getPosition

`position.x = 10;` is does nothing?
maybe then
`var position = this.entity.getPosition();` -> `var position = this.entity.getPosition().clone();`

**Comment by willeastcott** [comment]
Well, that example does work. But yeah, it's probably safer to clone the position.

**Pull request merged**
