### PR TITLE
Add optional name-parameter to Entity/Graph constructor

### PR DESCRIPTION
**Pull request by aidinabedi**
This PR saves lots of coding time by allowing developers to pass the entity name directly in the constructor. This not only minimizes tedious code but also makes its easier for the many that are familiar with Unity and/or porting code from Unity, see [`GameObject` constructor](https://docs.unity3d.com/ScriptReference/GameObject-ctor.html).

Please note that this still supports the old **undocumented** API of passing the `pc.Application` to the constructor. The PR is implemented to correctly handle the all use cases. In addition, the PR also documents all parameters (not just the new optional name) for both the `Entity` and `GraphNode` constructors and all exempels have also been updated to the comply with the documented API.

Summary of PR:
- Completely backwards-compatible.
- Full API documentation.
- Well tested!
- New optional APIs:
- - `new pc.Entity(name, app)` (old `new pc.Entity(app)` is still supported!)
- - `new pc.GraphNode(name)`

Please consider this important PR for us. Cheers

### CODE REVIEW

**Comment by Maksims** [comment]
One problem I have with this, is that it tries to change the behavior towards new approach too much.
What it should be instead, is to simply add override to Entity constructor, that allows passing name as first argument - which is what it is in PR, but with totally fine with no name provided.

So instead of treating "old" way as "legacy" and doing backwards-compatibility, instead do a new way as arguments overloading, and simply be fine with both ways.

**Comment by aidinabedi** [comment]
@Maksims Fair point. I've reverted changing all example usage of the Entity constructor. This simplifies the PR a lot.

Let me explain why I'm "trying" to push the new way as the primary approach instead of adding it as just an alternative approach. Because `Entity` inherits from `GraphNode`, they will share the same constructor parameters. However `GraphNode` has no knowledge of `pc.Application` and no need of such dependencies. So to add a constructor parameter that `GraphNode` wants (`name`), it should be first. Otherwise it will have to know about the other irrelevant parameter (`app`) that only `Entity` cares about.

So if you wish, a side from reverting the examples I can also change the new approach to just an alternative and remove the documentation, but that will IMHO result in less readable and confusing code. I just want PlayCanvas to have a more maintainable codebase in the long run :)

Cheers,

**Comment by Maksims** [comment]
It is important to keep such changes backwards compatible with current projects. And adding extra arguments should not break anything, indeed.

Name and application arguments both are optional.

**Comment by aidinabedi** [comment]
@Maksims Good point and great comments! I've updated the PR in accordance with your feedback :)

**Comment by Maksims** [comment]
Thank you a lot for contributing! :+1:

**Pull request merged**
