### PR TITLE
Defining component system's properties statically

### PR DESCRIPTION
**Pull request by yard**
Hi guys,

As discussed in https://github.com/playcanvas/engine/issues/790, please find a PR to address that.

**Changes**

- All engine's systems now define properties on the respective components in a static manner: one time at load phase
- Build file has been amended so that each component type is loaded before respective component system

**Why?**
Defining properties for every instance of every component has no benefits, but does damage performance.

Consider this simple benchmark:
```
var t0 = pc.now();
for(var i = 0; i < 1000; i++) {
    var box = new pc.Entity();
    box.addComponent("model", {
        type: "box",
    });    
}
var t1 = pc.now();
console.log("took " + (t1 - t0) + " ms");
```

On my machine running it on master branch takes 160–180ms (Chrome 55.0.2883.95 64-bit), 340–405ms (Firefox 50.1.0).
Running it on PR branch takes 85–120ms (Chrome), 280–300ms (Firefox 50.1.0).

Taking into account the PR doesn't affect the logic of properties in any way, it seems to be a solid gain from such a straightforward change :)

Hope this turns out to be helpful.

### CODE REVIEW

**Comment by Maksims** [comment]
Good, change, have you tested existing project if they are affected anyhow by this change?
One more notice, we have amended [CONTRIB.md](https://github.com/playcanvas/engine/blob/master/CONTRIB.md) to include more specific styling rules. If you be kind to check it out, as it relate to some code styling within this PR to be corrected to comply with Engine coding standards.

Otherwise, I will test some of our existing projects tomorrow, and if all good, after styling corrections will merge.

**Comment by yard** [comment]
Hi @Maksims,

Sure thing, will go over styleguide tomorrow. 

As for testing - sure, I did run the examples and a few my projects and noticed no issues; I don't think there should be any as the changes do not affect the behaviour in any way - but the more testing the better :)

**Comment by yard** [comment]
Hi @Maksims,

I have updated the pull request to comply with the style guide.

Please ping me if I am still missing anything.

**Comment by Maksims** [comment]
Thanks a lot for corrections. I've made some tests, and there is one issue where there are cases when people implement their own component systems. One of them is `spine`. So it was implemented relying on old system, so I've added few backwards compatibility things to make sure it still works with old components definition.
To test locally, fork [this](https://playcanvas.com/editor/scene/400271) project and download a build, replace engine with built from your PR.

So those changes will make it backwards compatible:

1. in [`components/component.js`](https://github.com/playcanvas/engine/pull/825/files#diff-96f81e4d2911b5b5d26f1f4045ccc987L17) bring back `buildAccessors` but with a check:
```javascript
if (this.system.schema && ! this._accessorsBuilt)
    this.buildAccessors(this.system.schema);
```

2. in [`_buildAccessors`](https://github.com/playcanvas/engine/pull/825/files#diff-96f81e4d2911b5b5d26f1f4045ccc987R25) method add a prototype property `_accessorsBuilt` so we can know if it has or not built a new accessors:
```javascript
prototype._accessorsBuilt = true;
```

3. and lastly [`buildAccessors`](https://github.com/playcanvas/engine/pull/825/files#diff-96f81e4d2911b5b5d26f1f4045ccc987L47) method shall be brought back.

This way old component system definitions will still work, and new ones use new system.  
You can add a `console.warn` to `buildAccessors` behind `debug` define to give warning saying that new accessors system shall be used.

Otherwise PR worked well on other cases, and after those changes will be ready to merge!

Спасибо! ;)

**Comment by yard** [comment]
Hi @Maksims,

I brought the logic back and added the fallback as per your suggestion. It seems to be working for me – please check on your side and let me know if you have any further issues.

The only thing I feel a bit uncomfortable about if that `_buildAccessors` and `buildAccessors` are quite similar in terms of logic, but I didn't find a way to use one method only – is it a big deal?

P.S. Не за что :)

**Comment by Maksims** [comment]
> The only thing I feel a bit uncomfortable about if that _buildAccessors and buildAccessors are quite similar in terms of logic, but I didn't find a way to use one method only – is it a big deal?

So if you add extra argument to _buildAccessors `dynamic`, and then mark `_accessorsBuilt` true only if `dynamic` isn't true:

```javascript
Component._buildAccessors = function (prototype, schema, dynamic) {
    // ...

    if (! dynamic)
        prototype._accessorsBuilt = true;
};
```

Then changing buildAccessors to:
```javascript
buildAccessors: function (schema) {
    Component._buildAccessors(this, schema);
},
```

Does the trick ;)

**Comment by Maksims** [comment]
Updated commnet above few times :D

**Comment by yard** [comment]
Hi @Maksims,
You were right – I just missed the meaning of `this` and thought it would get overwritten with your solution – but nvm and please check the latest version of the branch with the fix applied.

**Comment by Maksims** [comment]
Thank you very much again for making a PR! It feels really good when other developers go into, understand thing, and see how this can be made better.

**Comment by yard** [comment]
My please guys and thank you for your great work!

**Pull request merged**
