### PR TITLE
Update the examples browser to use PlayCanvas v1.44.0

### PR DESCRIPTION
**Pull request by ellthompson**
I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by mvaligursky** [comment]
I missed the change to CurveSet constructor .. is that going to cause compatibility issues with the existing projects, or do we handle both types?

**Comment by yaustar** [comment]
@mvaligursky Where did we change the curveset contstructor? 👀

**Comment by mvaligursky** [comment]
this PR changes the way the CurveSet instances are created - and so I'm making sure it's not a breaking change in the engine.

**Comment by yaustar** [comment]
@mvaligursky Added notes on the JSdocs change here: https://github.com/playcanvas/engine/pull/3265#issuecomment-876574263

**Comment by yaustar** [comment]
I'm reverting the JSDocs on the curveset so this should be valid again

**Comment by yaustar** [comment]
'Fixed' via: https://github.com/playcanvas/engine/pull/3319

**Comment by mvaligursky** [comment]
should you create a new PR? The comments on this don't match what it does .. ideally we should not reuse unrelated PRs.

**Comment by ellthompson** [comment]
Opened a new PR for the version bump here: https://github.com/playcanvas/engine/pull/3321

**Pull request closed without merging**
