### PR TITLE
change variables to local vars so "use strict" statement could work properly

### PR DESCRIPTION
**Pull request by shaochun**

### CODE REVIEW

**Comment by Maksims** [comment]
Could you please sign this [Contributors Agreement Form](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform), so we can merge your PR?
Thanks a lot for making a PR :)

**Comment by shaochun** [comment]
surely.

**Comment by Maksims** [comment]
Thank you a lot for making a PR! Feel free to make suggestions, request features and make more PR's :)

**Comment by shaochun** [comment]
glad to help :)

**Pull request merged**
