### PR TITLE
Added CC-BY-4.0 licences to asset viewer example

### PR DESCRIPTION
**Pull request by yaustar**
I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by mvaligursky** [comment]
you could also do it this way, to be more in line with other models we have?
https://github.com/playcanvas/engine/blob/main/examples/assets/models/chess-board.txt

**Comment by yaustar** [comment]
I would have thought we need to add it where it's being used?

**Comment by mvaligursky** [comment]
Not sure. This applies and does not specifies it: https://creativecommons.org/licenses/by/4.0/
I always though it better to be stored next to the file we distribute, rather than elsewhere where its referenced.

**Comment by yaustar** [comment]
I change it to be consistent to be the chess board for now. We can change it all later

**Comment by yaustar** [comment]
@mvaligursky Added text files for the licenses

**Review by mvaligursky — APPROVED** [review]

**Pull request merged**
