### PR TITLE
Make ObjectPool#freeAll() explicit

### PR DESCRIPTION
**Pull request by ertugrulcetin**
Reset `this._pool` array.

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by kungfooman** [comment]
The point of a pool is to pool objects. If you just empty `ObjectPool#_pool`, the pooled objects are gone.

When the engine tries to `ObjectPool#allocate`, it will return undefined:

image

image

In which way did you test this?

**Comment by ertugrulcetin** [comment]
@kungfooman I think it is correct now.

**Comment by LeXXik** [comment]
@ertugrulcetin The purpose of freeing the pool objects is to mark them available for reuse, not destroying them. Once you release all in the pool, the very first object that is already allocated in the pool becomes available the next time it is requested. There would be no new allocation taking place, hence the purpose of having a pool.

If you want to destroy all allocated objects and clear the pool, I would suggest to add a new method that would explicitly clear it.

**Comment by ertugrulcetin** [comment]
@LeXXik thank you for the explanation. It makes sense to me now.

**Pull request closed without merging**
