### PR TITLE
Include asset as optional parameter to Handler.load() and Handler.open()

### PR DESCRIPTION
**Pull request by aidinabedi**
**UPDATE 2:** Also include the optional asset-parameter to Handler.open(). See [last comment](https://github.com/playcanvas/engine/pull/693#issuecomment-278106637).

---

**UPDATE:** The 3rd optional parameter has been changed from `Asset.file` to `Asset` itself. Please [read my last comment here](https://github.com/playcanvas/engine/pull/693#issuecomment-236368326) for details and motivation!

---
### \- Previous pull request text -

**Description:**

Add optional 3rd parameter "`file`" to `*Handler`'s `load()` function. The parameter contains the `Asset`'s `file` object property.

**Motivation:**

Currently, there is no other way for custom handlers to know how to get a resource (aside for `Asset.file.url`, which is assumed to be relative). But by simply providing the `Asset.file` object as a an optional parameter, a handler can load resources from more a wider set of sources. This is not only because the `file.hash` (or `file.size`) is much more available/safely readable, but also because the `Asset.file` object can contain specific properties for different asset types. Further, and as previously touched upon, the `Asset.file.url` is assumed to be a non-absolute-url, since the `AssetRegistry.prefix` might be used as base path. Therefore, `Asset.file.url` it is not really compatible/safe to provide protocol schemes (such as "`ftp://`", "`git://`", "`websocket://`" etc) in the url. In addition, limiting resource loading to just a single url is also rather arbitrary, and not that useful for the following use cases:
- Depending on what the GPU or browser supports, you need alternative urls to fetch the same image but in different formats, like DXT (typically only supported on desktop), ATC (typically only supported on mobile), ETC1, PVRTC, WEBP etc).
- Some of your assets are procedural and need to be loaded asynchronously, using the asset API just like any other assets. The necessary seed information is  available in `Asset.file`.
- You not only need to know the protocol for the asset your are fetching, but additionally a user/password/hash/json which you don't want to cumbersomely parse from an url, which is error-prone or you just don't wish to expose it in the url.
- In our use case, aside from the url we need a arbitrary json object which affects the way we fetch & read the response, this has to be done in either in the handler's load or open call because the result is forwarded to built-in handlers.

**API changes:**
- `*Handler.load(url, callback)` -> `*Handler.load(url, callback, file)`

**Implementation:**

The implementation is ridiculously simple, `AssetRegistery.load` and `ResourceLoader.load` simply pass the value of `Asset.file` as a 3rd optional "`file`" parameter to all handlers' load function, [see first commit](https://github.com/playcanvas/engine/pull/693/commits/f9429ac249e353bbf42d338a43b6d0172977f488). I've also added the parameter (unused) to all built-in handlers, [see second commit](https://github.com/playcanvas/engine/pull/693/commits/07cdf9abbdc5f4e88872a5b8925511f553bce0e4).

**Alternative solutions:**
1. Pass the entire `Asset` object as a 3rd optional parameter instead of just `Asset.file`. This is more general but also feels to powerful and might encourage devs to mess around too much with the state of the asset while async loading it.
2. Pass the entire `Asset.file` object as the 1st param instead of just `Asset.file.url`. This is would be preferably as it's definitely more general but would require the file object to still behave like a string for backwards-compatibility (implement `toString()` etc) and to properly be translated into a cache/request key internally in the `ResourceLoader`. However this is a bigger change and might break the API.
3. Pass `Asset.file` (or the entire `Asset`) to `Handler.open(url, data, *file*)` instead of `Handler.load`. The problem with this solution is that you can't customize the async fetch phase which is supports more use cases.

### CODE REVIEW

**Comment by daredevildave** [comment]
Thanks Aidin for the very thoroughly researched PR :-) We encountered a similar issue when looking into supporting audio streaming assets. So I'm aware of the problem. 

That said I have a few problems with this PR.

1. asset.file is a specific format and I don't think it is the correct object to pass around in this case. asset.data is general asset data (format defined by the asset type) and would probably be a better fit.
2. The resource loaders are designed to be independent of the assets system until the "patch" method. This is so that users can use a simple call to `app.loader.load(url, type, callback)` and load resources without the boilerplate of creating assets. I'd like to keep that.
3. I would always keep the callback as the final argument. This would require a check in the function to skip the missing argument but I think the exposed API is nicer.

As I see it, the main issue with the resource loader is that for a given combination of asset type and file url/extension. There is no way to indicate different loading methods.

In terms of your use-cases:

a. We're are planning to support "asset variants" for texture formats and LODs. It's not completely clear at the moment whether these would all be a single asset (1 id/url, 1 data block) or multiple assets (many ids/urls, many data blocks). For example, different texture formats can already be loaded differently as their URLs/extensions differ. Though this doesn't work for LODs. But if we add passing in asset.data, then we need to store all the information about variants in asset.data. Which I'm not sure is correct.

b. I see no reason why procedural resources couldn't be created with the existing system. It would require a new asset type and handler combination, but it should all work.

c. This is a valid case for adding additional information to the load request. This probably shouldn't be stored in asset.data though.

d. This is also a valid case for adding additional information to the load request. It depends on your circumstances, does this data belong in asset.data?

So..., my feeling is we need to figure out how asset variants are going to work. @Maksims has been thinking most about this. Then if it still makes sense we many need to pass asset.data into the `Handler.load` method. Which would allow assets to specify particular methods of loading.


Aside: the asset.file.url field should support absolute URLs. This is a separate issue though, perhaps you could raise an issue for that?

**Comment by aidinabedi** [comment]
> 1, asset.file is a specific format and I don't think it is the correct object to pass around in this case. asset.data is general asset data (format defined by the asset type) and would probably be a better fit.

I agree that `Asset.data` is better suited to be passed around generally. But in the case of `Handler.load`, I would argue that `Asset.file` might be the correct object, since it already contains properties (like hash) which you might specifically need when fetching resources from an asset server . However, as you point out it is definitely ugly (and maybe error-prone in the future) to fill it with arbitrary stuff. So `Asset.data` is more correct, although maybe both would be good to pass.

> 2, The resource loaders are designed to be independent of the assets system until the "patch" method. This is so that users can use a simple call to app.loader.load(url, type, callback) and load resources without the boilerplate of creating assets. I'd like to keep that.

I fully respect and support your wish to keep the ability to let users make a simple call to app.loader.load without boilerplate. That is why the new parameter is optional and it's the handlers responsibility to handle ;) it correctly. Just like when the `url` parameter in `Handler.open` is always null if called using `app.loader.open()`.

> 3, I would always keep the callback as the final argument. This would require a check in the function to skip the missing argument but I think the exposed API is nicer.

I support that.

> a. We're are planning to support "asset variants" for texture formats and LODs. It's not completely clear at the moment whether these would all be a single asset (1 id/url, 1 data block) or multiple assets (many ids/urls, many data blocks). For example, different texture formats can already be loaded differently as their URLs/extensions differ. Though this doesn't work for LODs. But if we add passing in asset.data, then we need to store all the information about variants in asset.data. Which I'm not sure is correct.

By adding `Asset.data` (or `Asset.file`) as a optional parameter in Handler.load, you would allow customers that need "asset variants" and LODs (like us) to implement it ourselves right now. Big new features usually take time to mature and design correct. In the meantime it would be great to have a workaround.

> b. I see no reason why procedural resources couldn't be created with the existing system. It would require a new asset type and handler combination, but it should all work.

The problem is that the procedural resource is generated asynchronously, based on seed input/value(s). Because the generation is async it must happen when it's custom handler.load is called. But how does the custom handler know which input values to use for this particular asset? Obviously it could load them from a file the url points to but that is completely unnecessary loading time for data that is small enough to fit in Asset.data.

> c. This is a valid case for adding additional information to the load request. This probably shouldn't be stored in asset.data though.

I agree, this supports the case for passing both the Asset.data and Asset.file.

> d. This is also a valid case for adding additional information to the load request. It depends on your circumstances, does this data belong in asset.data?

It is an edge case. The additional information contains an override json object that is merged with the url-file content. I would prefer it to be in asset.file since in most cases our handlers forwards calls to built-handlers which expect asset.data be contain specific information.

> So..., my feeling is we need to figure out how asset variants are going to work. @Maksims has been thinking most about this. Then if it still makes sense we many need to pass asset.data into the Handler.load method. Which would allow assets to specify particular methods of loading.

I urge you to please add a workaround while the design for asset variants are being worked on. It is a completely valid and sufficient workaround to just pass Asset.data to load. It would help us and other customer to have workable solution in the short term. A great solution takes time and it's better to not rush big design changes. That is why I designed this PR as a non-breaking API, as a short term solution.

> Aside: the asset.file.url field should support absolute URLs. This is a separate issue though, perhaps you could raise an issue for that?

Will do!

**Comment by aidinabedi** [comment]
Hello @daredevildave!

Has @Maksims had a chance to look at this PR?

We've been thinking more about this request, the use cases and your planned feature "asset variants". We've actually stumbled upon a new even more important use case - which I'll explain below. First I must inform you that I unfortunately can't see that "asset variants" will be enough.

In fact, "asset variants" might help in only 1 of the 4 previously mentioned use cases. The 5th new use case is a big one:

* When you finish loading a non-preloaded asset, it is not guarantied to be completely loaded, since it may depend on other non-preloaded assets such as in the case of a material or model. This causes a problem if the asset.resource needs to be cloned (which it does in many cases, including ours). We need to create separate instances of a material so we can change color for isolated objects without changing the color for all objects sharing the material. However this will causes a race condition. If the asset (e.g. material, model) is cloned before assigning the referenced textures, the clone will be incomplete. The best solution is thus to let our custom MaterialHandler.load preload all referenced assets in our material.


This use case together with our discussions have made me realize that this PR has to be even more general. I have thus changed so that the 3rd optional parameter is the `asset` itself instead of just `asset.file` or `asset.data`. This is so that the PR can supports a wider range of use cases and makes no assumption about whether the `*Handler.load` function should be limited to `asset.file` or `asset.data`.


P.S. I've [submitted a fix for supporting absolute asset urls](https://github.com/playcanvas/engine/pull/704), as promised.

Please respond :)

**Comment by aidinabedi** [comment]
Please re-review my changes. I've made the PR simpler and also pass the `Asset` as an optional parameter to `Handler.open(url, data, *asset*)`. This allows for even more flexibility for developers and applications that need custom handlers.

Please consider this PR. Sincerely,
Animech Technologies.

**Comment by Maksims** [comment]
Tested on few project, merged.
Thank you for simplifying PR a lot and sorry for not acting on it that soon.

**Pull request merged**
