### PR TITLE
Added teleportOrientation method to rigidbody

### PR DESCRIPTION
**Pull request by sethgillett**
Tested the method in the editor and it works fine.
#782

### CODE REVIEW

**Comment by willeastcott** [comment]
This function is just an alias for:

this.entity.rigidbody.teleport(this.entity.getPosition(), rotation);

So I don't quite understand why it's needed.

**Comment by sethgillett** [comment]
Ah my bad, so to clarify was there an agreed upon solution for the setPosition() setRotation() methods syncing up with the rigidbody? Why not just have setPosition and setRotation call the corresponding rigidbody methods? Something roughly like:
```javascript
// entity.js
setPosition: function(x,y,z)  {
    // ...
    if (this.rigidbody) {
        this.rigidbody.syncEntityToBody()
    }
}
```
And then just deprecate ```rigidbody.teleport()``` altogether.

**Comment by willeastcott** [comment]
Because pc.Entity should not have a dependency on pc.RigidBodyComponent. Architecturally, that's a bad idea.

One solution could be that calling setPosition/Rotation on a pc.Entity fires an event ('setposition', 'setrotation', or maybe just 'updatetransform') and the RigidBodyComponent listens on that. But the concern there is that firing an event on every update to the transform of an entity would impact performance quite considerably.

**Comment by sethgillett** [comment]
Ah, I see the issue. I guess in that case, the addition of a ```teleportOrientation()``` method is unnecessary. Could a potential fix be that the rigidbody component throws an error if the entity's transform is directly altered? That would get rid of the confusion at least.

**Pull request closed without merging**
