### PR TITLE
Post Process God Rays

### PR DESCRIPTION
**Pull request by leonidaspir**
It introduces a post effect that can simulate light shafts (god rays) from a world point. The screen position is derived from the position of the referenced entity (it doesn't require a light component). Multiple instances of the effect can be added. The Post Effects example has been updated.

image

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by mvaligursky** [comment]
Fantastic work on these @leonidaspir!
I just wonder .. this one PR seems to include multiple effects, some already in different PRs .. is that intentional?

**Comment by leonidaspir** [comment]
> I just wonder .. this one PR seems to include multiple effects, some already in different PRs .. is that intentional?

Good point, no :) I can clean up each individual PR to include only the posteffect-[pp-name].js script and make a separate PR for the updated post effects example that includes all the new effects. Would that work better?

**Comment by mvaligursky** [comment]
yes that would work much better .. this will just give us merge issues.
You could even bundle 2-3 effects together possibly to make it easier on yourself.

**Comment by leonidaspir** [comment]
@mvaligursky I think everything has now been cleaned. Each effect PR contains only the new file and another temp file (post-effects-private.html) for testing it.

**Comment by mvaligursky** [comment]
closing - new PR https://github.com/playcanvas/engine/pull/3272

**Pull request closed without merging**
