### PR TITLE
Chore: var to const in math

### PR DESCRIPTION
**Pull request by LeXXik**
Changes `var` to `const` in the comments of math classes.

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by kungfooman** [comment]
image :+1:

**Comment by mvaligursky** [comment]
This PR has no changed files, problem creating this @LeXXik ?

**Comment by mvaligursky** [comment]
@willeastcott - a while back we wanted to leave `var` instead of `let` and `const` in the JSDocs examples, mostly to help users that write our ES5-based scripts. 
But I think it's time to fully abandon `var` in the code base now.

**Comment by willeastcott** [comment]
@mvaligursky The API ref dumped `var` long, long ago. 😄  Even IE11 support `let` and `const`!

**Comment by Maksims** [comment]
> @mvaligursky The API ref dumped `var` long, long ago. 😄 Even IE11 supports `let` and `const`! TBH, we should probably update the provided skeleton script in the Editor to use `const` at some point.
> 
> I'm assuming @LeXXik hadn't pulled his fork for a while.

There will be a problem with const when defining script type, loading and unloading it. It will lead to exception due to redefinition. 😕

**Comment by LeXXik** [comment]
Great PR. Closing.

**Pull request closed without merging**
