### PR TITLE
Fix for NaN rotation Quat build from zero Mat4

### PR DESCRIPTION
**Pull request by e-strokov**
An entity zero scale caused rotation become NaN.
It's better to keep Quat unchanged to retain original rotation value.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by vkalpias** [comment]
Does that fix issues with other things in the Editor as well like using the gizmos of an entity who has zero scale either directly or through a parent's transform?

**Comment by e-strokov** [comment]
@vkalpias I've tried reparent, translate, add children, rescale, remove children, reparent and so on.... And it seems to work as I'd expect in case of zero scale. Anyway, it worth someone else also test this.

**Comment by vkalpias** [comment]
Great! I'll give it a test too

**Comment by vkalpias** [comment]
I did some tests and the problem with gizmos is probably a different matter that we have to handle outside of the scope of this PR. e.g. if you select an Entity with zero scale and click the button to switch to Local space gizmos then some of them disappear or don't work at all. 

On this PR should we add a unit test about what happens to quaternions with zero scale?

**Comment by e-strokov** [comment]
@vkalpias I've added a unit test.

**Pull request merged**
