### PR TITLE
Update asset_asset.js

### PR DESCRIPTION
**Pull request by PsichiX**
ASSET_SHADER, ASSET_CSS and ASSET_HTML constants added

### CODE REVIEW

**Comment by Maksims** [comment]
Could you please sign [this Contributors Agreement form](https://docs.google.com/a/moka.co/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform), so we can merge your PR?
Thanks a lot for making a PR :)

**Comment by PsichiX** [comment]
@Maksims: ok, done :)

**Comment by daredevildave** [comment]
Sorry, @PsichiX you need to complete the form completely. 

It's important to protect the library from claims by any third-party and ensure that the engine license can be maintained into the future. I realize that it's a bit of a pain, but it's a legal necessity.

You can be assured that any data provided is confidential and will not be shared.

**Comment by PsichiX** [comment]
@daredevildave: ok, new agreement was sent.

**Comment by Maksims** [comment]
Thank you very much for a PR! :) Feel free to make more of them, or ask question and request features.

**Comment by PsichiX** [comment]
+1

**Pull request merged**
