### PR TITLE
[DOC] Add documentation for more resource handlers

### PR DESCRIPTION
**Pull request by aidinabedi**
PR improves jsdoc comments for the following already documented resource handlers:
- `pc.ModelHandler`
- `pc.ScriptHandler`
- `pc.BundleHandler` (still private)

PR also adds jsdoc comments for the following currently undocumented resource handlers:
- `pc.AnimationHandler`
- `pc.AudioHandler`
- `pc.CubemapHandler`
- `pc.FontHandler`
- `pc.MaterialHandler`
- `pc.SceneHandler`
- `pc.SpriteHandler`
- `pc.TextureAtlasHandler`
- `pc.TextureHandler`

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
Interesting that two handlers are public API and the others aren't. There is an argument that we make ```pc.ScriptHandler``` and ```pc.ModelHandler``` private rather than making the other 9 public. Adding 9 will (IMHO) just pollute the API ref with stuff that developers will never actually directly use or need to refer to. @daredevildave, what's your opinion?

**Comment by aidinabedi** [comment]
I haven't documented these just for kicks :)

And if you look at [old 3rd-party documentation others have done (by hand), we're not alone in needing declarations for these resource handlers](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/playcanvas/engine/resources).

Besides, you have already publicly documented the function that registers custom handlers, [pc.ResourceLoader.html#addHandler](https://developer.playcanvas.com/en/api/pc.ResourceLoader.html#addHandler)

Begin able to extend and wrap resource handlers is a key feature for us that we need type info for.

**Comment by willeastcott** [comment]
Yeah, but all existing handlers are registered in the pc.Application constructor. The user can't edit/modify that code. The only use for ```pc.ResourceLoader.html#addHandler``` is to add your own handler types.

**Comment by aidinabedi** [comment]
We extend the existing handlers by wrapping them in our own handlers (which we register), without having to re-implement all the functionality.

**Pull request merged**
