### PR TITLE
Shader precision optimizations

### PR DESCRIPTION
**Pull request by raytranuk**
WIP 
- final naming of the macros to be decided
- visual results so far:

Before:
image

After:
image

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
Wouldn't it be easier to use default precision qualifiers at the top of the shader, and then only explicitly override the default where something breaks?

**Comment by raytranuk** [comment]
Using default precision was the approach taken in the initial investigation: https://github.com/playcanvas/engine/issues/2596 - however, after discussion in the graphics sync it was agreed (I think) that it would be better to opt-in shader chunks - as it was felt that some precision problems will only be visible after extensive testing and there was a danger of things slipping through if applied globally.

**Comment by willeastcott** [comment]
I think I missed that discussion. If it was me, I would make use of the default qualifiers and then fix specific vars as required. Kinda like we do for GPU skinning precision.

Keeps the code cleaner, leaner, more readable and more maintainable. I literally don't think I've seen any GLSL in my life that specifies a precision for every single possible thing.

**Comment by mvaligursky** [comment]
Yes we discussed this and decided it would be easier to leave fragment shaders on the default high precision, and locally drop parts of the code that we know does not need it to medium precision. Going the other way would created a lot more issues that would be hard to solve. This way we have better control over it and can progressively optimize other chunks as needed.

**Comment by mvaligursky** [comment]
In a way this is similar to the way HLSL handles this .. they expose float and half types (including float2, 3, 4 and half2, 3, 4) .. So this is the define we discussed as possible option today - that would keep the code clean, we'd just `#define half mediump float` and similar

**Comment by mvaligursky** [comment]
looking at PR .. I'd suggest we change line 
`MMEDP vec2 uv = $UV;`
to
`half2 uv = $UV;`

**Comment by slimbuck** [comment]
Agree @mvaligursky, that would clean the code up nicely. Though we might have to be careful that the expanded expression 'mediump float' does not cause unexpected errors.

**Comment by raytranuk** [comment]
The defines currently used in this WIP draft PR are definitely temporary - the grouping is to help me debug and test - I kinda mentioned in the graphics sync I was leaning towards `hfloat` `hvec2` - but `half` and `half2` is also a possibility - though less consistent with GLSL? We could also consider aliasing `vec2` for `float2` if we wanted to go full on HLSL?

**Comment by raytranuk** [comment]
And @slimbuck is right - precision qualifiers can only be used in certain situations - which makes things less straight forward...

**Comment by mvaligursky** [comment]
yes .. when I add some shader code here, I always do float4 instead of vec4 .. and then fix it. So I'm definitely keen on hlsl styling :)
so I guess there's code like this to handle:
`half2 uv = half2(data.x, 0.0);`
I assume the right hand side cannot use precision qualifier? So we use just vec2 there?
Are you aware of some other expctions @raytranuk ? or do we use half when declaring variables, and vec the rest of the time?

**Pull request closed without merging**
