### PR TITLE
Add npm support

### PR DESCRIPTION
**Pull request by scarletsky**
Refer to https://github.com/playcanvas/engine/pull/832, add npm support for playcanvas.

**Update:**

For those guys who want to install an unofficial playcanvas, you can try:

```
npm install @scarletsky/playcanvas
or
npm install @scarletsky/playcanvas --no-optional

$ node
> const pc = require('@scarletsky/playcanvas')
undefined
> pc.Vec3
[Function: Vec3]
> pc.math
{ DEG_TO_RAD: 0.017453292519943295,
  RAD_TO_DEG: 57.29577951308232,
  INV_LOG2: 1.4426950408889634,
  clamp: [Function: clamp],
  intToBytes24: [Function: intToBytes24],
  intToBytes32: [Function: intToBytes32],
  bytesToInt24: [Function: bytesToInt24],
  bytesToInt32: [Function: bytesToInt32],
  lerp: [Function: lerp],
  lerpAngle: [Function: lerpAngle],
  powerOfTwo: [Function: powerOfTwo],
  nextPowerOfTwo: [Function: nextPowerOfTwo],
  random: [Function: random],
  smoothstep: [Function: smoothstep],
  smootherstep: [Function: smootherstep],
  intToBytes: [Function: intToBytes32],
  bytesToInt: [Function: bytesToInt32] }
>
```

Happy hacking 😄  !

### CODE REVIEW

**Comment by willeastcott** [comment]
Hey, @daredevildave, what should happen with this PR? I've seen several folks ask about npm support. Any thoughts/feelings on this?

**Comment by JarnoVgr** [comment]
Bump. It would be great to have official npm support. :)

**Comment by willeastcott** [comment]
I want to understand more about this. Currently, the build.js file generates a package.json. What is that? Should we be checking it in? If we do, we'll have the engine version number checked in, which means we must edit the package.json every time we do a release. If we check in the package.json, does that mean we should start checking in builds of the engine? Do we have to register the PlayCanvas engine in some NPM registry somewhere?

**Comment by scarletsky** [comment]
@willeastcott Sorry for the delay.

If you want to publish your libraries to npm, you need to register an account in npm. And then you can publish whatever you want to it. Other users can download it by `npm install xxx`.

> Currently, the build.js file generates a package.json. What is that? Should we be checking it in?

Generally, we should put the `package.json` at the root of the project. If you put it at subfolder, developers would consider it as the submodule of the project. But in `playcanvas/engine`, the build folder is just the build folder, not any submodule of the project. So I think we'd better put the `package.json` at the root of the project.

> If we do, we'll have the engine version number checked in, which means we must edit the package.json every time we do a release.

Yes, this is very common in Node.js usage. As developers can specify which version they want to use. What a library author should do is just to update the version of `package.json` and then publish to npm, that's it.

**Comment by scarletsky** [comment]
I've add umd-wrapper for the output file, so that developers can require playcanvas without error.
But the cons is that require `jsdom` as dependences.

**Comment by JarnoVgr** [comment]
Sorry for bumping this again. Would really like to see this happen. :)

**Comment by scarletsky** [comment]
@JarnoVgr 
That's very strange. When I publish `0.220.0`, it works. However, I merge `0.221.0` and publish a new version, it sucks...

I think JSDOM should be a optional deps too.

**Comment by JarnoVgr** [comment]
@SHADOWELITE7 NPM is a package manager for open-source JS libraries. This allows end-users for tighter integration in their existing website/app/web-game workspace.

**Comment by SHADOWELITE7** [comment]
ooh that actually is very cool, thx for letting me know about it @JarnoVgr

**Comment by Tatsujinichi** [comment]
I would like to see this happen as well, but I am not sure this is the right way to go about it.  Ideally you would want to have something like Rollup replace the current build.  The package.json should not be generated. IMO

**Comment by scarletsky** [comment]
@JarnoVgr 
I know why the `0.221.0` release miss the `build/` folder now. Because I run the build process in the master brunch, and it generate `package.json`. When I switch to my brunch, the `package.json` is still in `build/`. When `npm pack`, it will ignore the folder which contains `package.json`.

**Comment by scarletsky** [comment]
@Tatsujinichi Do you have any idea how can we require playcanvas engine in Node.js environment?

**Comment by ronkorving** [comment]
Regarding versioning hassle, you can use `npm version patch|minor|major` to do the following in 1 shot:

- bump the version number in package.json at the given level (patch, minor, major)
- tag your branch with the version number it became

**Comment by ronkorving** [comment]
I'm trying to debug an issue right now which may or may not be a PlayCanvas bug. I'm stuck with a minified engine file, which doesn't work. If PC was properly integrating into my project via package.json (ie: via NPM), it would not minify during development and my stack traces would be so much more readable.... I think this PR would make a lot of people happy. I know it would make my life a lot easier.

**Comment by scarletsky** [comment]
@ronkorving 
I think the main problem is how can `pc` run in Node.js environment. 
This PR use `jsdom` as optional dependence, which will include a lot of dependencies when you run `npm install @scarletsky/playcanvas`.

**Comment by JarnoVgr** [comment]
@ronkorving You could download both minified and normal file and put them next to each other. Some IDEs auto-detect the normaal version when you include the minified one in your HTML, which should make development easier as well. However, stacktraces/sourcemaps etc. are still somewhat wrong.

**Comment by ronkorving** [comment]
@JarnoVgr Absolutely, but do you know where I can get the non-minified file?

**Comment by JarnoVgr** [comment]
They're in the `README.md`/project page.

E.g.
Non-minified: `https://code.playcanvas.com/playcanvas-latest.js`
Minified: `https://code.playcanvas.com/playcanvas-latest.min.js`

**Comment by scarletsky** [comment]
@ronkorving You can also use the non-minified version in your development, and minify it with uglifyjs by yourself.

**Comment by ronkorving** [comment]
@scarletsky It would be nice if the REST API that I use to download my project would include both the minified and non-minified versions :)

**Comment by willeastcott** [comment]
Hi everyone. Sorry it took so long to merge this. Better late than never. 😉 

I'm also now wondering if we should move to rollup...

**Comment by scarletsky** [comment]
@willeastcott Do you agree with the `jsdom` as optional dependence ?

**Comment by Tatsujinichi** [comment]
Also check out webpack.

**Comment by willeastcott** [comment]
To be honest, @scarletsky, I'm not sure about jsdom.

I just looked at rollup and webpack. Despite webpack seeming to be more popular, rollup seems to be designed specifically for building and distributing JS libraries so I feel it's probably a better fit. With rollup, you can build a library for both Node and general browser usage. It would involve quite a significant edit to the sourcebase though.

**Comment by scarletsky** [comment]
@willeastcott 
Some articles say webpack is better when you build application, while rollup is good for libraries.
The PlayEngine framework also use rollup as build tool. 😃 

https://github.com/scarletsky/playengine/blob/master/rollup.config.js

**Comment by willeastcott** [comment]
Hey, @scarletsky, I want to remove jsdom from the dependencies here. With some small tweaks to the engine and by creating a small script to mock the Canvas/WebGLContext objects in the browser, PlayCanvas should work just fine. I'm going to test this but so far, it seems to work fine. Let me know if you have any objections.

**Comment by scarletsky** [comment]
@willeastcott 
That's a good choice. I think `jsdom` is useless too.
I used to add `jsdom` because I want to `require` playcanvas in Node.js.
But with bundler's help, it seems we can `require` playcanvas easily.
For example, in webpack, just use the following code:

```js
// webpack.config.js
new webpack.ProvidePlugin({
    pc: ['playcanvas', 'pc']
}),

// main.js
if (process.env.NODE_ENV === 'production') {
    global.pc = pc;
}
```

It can inject pc to our codebase without any hack. That means [umd-wrapper](https://github.com/playcanvas/engine/blob/master/build/umd-wrapper.js) no longer needed. 😃

**Comment by scarletsky** [comment]
Another tips is we can add `@playcanvas` scope in the `name` field in `package.json`:

```diff
- "name": "playcanvas",
+ "name": "@playcanvas/engine",
```

Users can run `npm install @playcanvas/engine` instead of `npm install playcanvas`.
With the scope, you can also publish `@playcanvas/playcanvas-gltf`, `@playcanvas/xxxx` 😃

**Comment by willeastcott** [comment]
OK, check out [this work in progress PR](https://github.com/playcanvas/engine/pull/1579). I'm close to being able to create a pc.Application without needing window or navigator.

As for the name scoping, interesting idea! This work is finally leading up to me publishing the engine on npm, so deciding on a naming convention is important.

**Pull request merged**
