### PR TITLE
[DOCS] Make scrollbar API reference docs public

### LINKED ISSUE #1729: [DOCS] Scrollbar component is undocumented
pc.ScrollbarComponent is marked as private API and is also undocumented, editor help on the component's members leads to empty reference pages, like https://developer.playcanvas.com/en/api/pc.ScrollbarComponent.html#orientation

### PR DESCRIPTION
**Pull request by willeastcott**
Fixes #1729.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by ElsaMeng** [comment]
if(this.entity.scrollbar){              
        this.app.on('set:value',function(value){        
            this.updateValue(value);
        });      
    }

**Comment by ElsaMeng** [comment]
if(this.entity.scrollbar){              
        this.app.on('set:value',function(value){        
            this.updateValue(value);
        });      
    }

**Comment by ElsaMeng** [comment]
hello, guys,I already make a scrollbar, but u see up there, it doesn't execute the function.I am confused.So how to use the event 'set:value'.Please help.Thanks a lot.

**Comment by ElsaMeng** [comment]
hello, guys,I already make a scrollbar, but u see up there,when I grab the handle to change the value, it doesn't execute the function.I am confused.So how to use the event 'set:value'.Please help.Thanks a lot.

**Comment by willeastcott** [comment]
I think you mean to do:

```
if (this.entity.scrollbar) {
    this.entity.scrollbar.on('set:value', function (value) {
        this.updateValue(value);
    });
}
```

**Comment by ElsaMeng** [comment]
it works.Thanks again :)

**Pull request merged**
