### PR TITLE
[Bug Fix] Initialize default attribute values when creating a script

### LINKED ISSUE #1052: Default attribute values are ignored when creating a script
If you fail to pass attribute values when creating a script on a script component, attributes will be undefined. This is not helpful or desired. If a script writer has taken the trouble to specify sensible defaults, they should be used if values are not passed in code. 

So instead of:

                camera.script.create('orbitCamera', {
                    attributes: {
                        inertiaFactor: 0,
                        distanceMin: 0,
                        distanceMax: 0,
                        pitchAngleMax: 90,
                        pitchAngleMin: -90,
                        frameOnStart: true
                    }
                });

,,,where the attributes specified are already the defaults in the script, you should just be able to do:

                camera.script.create('orbitCamera');

### PR DESCRIPTION
**Pull request by aidinabedi**
Fixes #1052

PR includes two changes:

1. Remove unnecessary nullification of a falsy `args.attributes` at [script/component.js:517](https://github.com/playcanvas/engine/blob/dc968f28400b618c5c53bcb4187cba54312c53d6/src/framework/components/script/component.js#L517) (since this is already being done at [script/script.js:344](https://github.com/playcanvas/engine/blob/dc968f28400b618c5c53bcb4187cba54312c53d6/src/script/script.js#L344))

2. Proper bugfix for #1052, which replaces a falsy `args.attributes` with `{ }` instead of `null` at [script/script.js:344](https://github.com/playcanvas/engine/blob/dc968f28400b618c5c53bcb4187cba54312c53d6/src/script/script.js#L344). This will ensure that `__initializeAttributes` does actually initializes default attributes instead of aborting due to `args.attributes` being falsy.

----

The bugfix can easily be tested using a publically available playcanvas project (simply run it with and without the PR): https://playcanvas.com/project/582708/overview/defaultattributestest

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Without PR:**
bug_fixed_no

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**With PR:**
bug_fixed_yes

----

To understand this bugfix in detail, please follow the code path starting from `pc.ScriptComponent.create` until the end of `__initializeAttributes` - using the code snippets below.

Current code for `pc.ScriptComponent.create` starting at [script/component.js:496](https://github.com/playcanvas/engine/blob/dc968f28400b618c5c53bcb4187cba54312c53d6/src/framework/components/script/component.js#L496):
```javascript
        create: function (name, args) {
...
                    var scriptInstance = new scriptType({
                        app: this.system.app,
                        entity: this.entity,
                        enabled: args.hasOwnProperty('enabled') ? args.enabled : true,
                        attributes: args.attributes || null
                    });
...
                    if (!args.preloading)
                        scriptInstance.__initializeAttributes();
...
        },
```

Current code for `new scriptType` and `__initializeAttributes` starting at [script/script.js:329](https://github.com/playcanvas/engine/blob/dc968f28400b618c5c53bcb4187cba54312c53d6/src/script/script.js#L329):
```javascript
        var script = function (args) {
...
            this.__attributesRaw = args.attributes || null;
...
        };

...

        script.prototype.__initializeAttributes = function (force) {
            if (!force && !this.__attributesRaw)
                return;

            // set attributes values
            for (var key in script.attributes.index) {
                if (this.__attributesRaw && this.__attributesRaw.hasOwnProperty(key)) {
                    this[key] = this.__attributesRaw[key];
                } else if (!this.__attributes.hasOwnProperty(key)) {
                    if (script.attributes.index[key].hasOwnProperty('default')) {
                        this[key] = script.attributes.index[key].default;
                    } else {
                        this[key] = null;
                    }
                }
            }

            this.__attributesRaw = null;
        };
```

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by aidinabedi** [comment]
Anyone had a chance to look at this?

**Comment by willeastcott** [comment]
Hi @aidinabedi - sorry that this hasn't been merged yet. It's fantastic that you've submitted a fix for this. Although the amount of code that has changed is small, we're going to have to schedule some very thorough testing to ensure that it's safe to deploy. We're working on asset bundles just at the moment, but we'll do it straight after that. Thanks for being patient with us - we appreciate the contributions! 😄

**Comment by vkalpias** [comment]
This PR also seems to fix https://github.com/playcanvas/engine/issues/949

**Comment by aidinabedi** [comment]
Hello @vkalpias, any updates?

Unfortunately, we can't provide any more suitable projects for testing simply because our complicated build process is almost entirely outside PlayCanvas, aside from downloading 3D assets. I'm curious as to why you want more projects besides the unit tests and the already provided project above? Surely that and reviewing the 2 lines of changes should be enough no?

**Comment by aidinabedi** [comment]
Hello @willeastcott and @daredevildave!

Any chance one of you guys could maybe take a look at this old PR?

**Comment by willeastcott** [comment]
Finally merging this - wow, thanks for being patient with our slowness on this. You're amazing!

**Pull request merged**
