### PR TITLE
Fix bug preventing default attributes if instance attributes not defined

### PR DESCRIPTION
**Pull request by aidinabedi**
This simple PR just removes a bad check, that will incorrectly abort initialization of attributes just because the instance attributes "holder" object (i.e. `__attributesRaw`) is not defined. Even if the instance attributes object `__attributesRaw` is not defined, default attributes should still be assigned to a newly created script instance. In addition, the check is also redundant since it is being done (correctly) later in the same function.

### CODE REVIEW

**Comment by Maksims** [comment]
Hm.. I'm really liking that you actually go deep into guts of engine, and getting a grasp on things!

Will have a look into that a bit more precisely. Reasoning of that check was to prevent that method from executing unless there are really a need to set attributes, and defined `__attributesRaw` was an indicator of that. There are quiet a few scenarios where `__initializeAttributes` is called from, and will need to test all those cases first to make sure we do not do unnecessary initialising of default attributes multiple times, as well as attributes are still available when they are needed.

If there were a particular problematic scenario that lead to this change?

**Comment by aidinabedi** [comment]
Thank you for your kind words, @Maksims!

I've actually written a complete Unity3D prefab to PlayCanvas converter (including dependencies). I work for [Animech Technologies](http://www.animechtechnologies.com/), I believe some of your colleagues have meet some of mine :)

Anyway, the check I removed in the PR, is causing default attributes for scripts instantiated in run-time (using `entity.scripts.create('MyScript')`) to not be assigned. Obviously a possible workaround is to just pass a empty custom attributes like `entity.scripts.create('MyScript', { attributes: {} })`, but that is not a obvious workaround and shouldn't be necessary IMHO :)

I understand the optimization aspect. Another way to fix this scenario more specifically would be to change the following line in `/src/framework/components/script/component.js`:

- [`attributes: args.attributes || null`](https://github.com/playcanvas/engine/blob/fac2cd95bfa6dd7c43c4a917827880ed69470b58/src/framework/components/script/component.js#L321) -> `attributes: args.attributes || {}`

I can update my PR. What do you think?

**Comment by Maksims** [comment]
I need to test few things, there were complicated scenarios that lead to this reason, and they are that you can use default values for example "resource_id" for entity type attribute, or asset id, but you can't guarantee that entity or asset will be available during creating of script instance on script component, as that happens way before final initialisation process. Which then leads to racing condition of what gets first and where.

That's why there was a decision to delay attributes initialisation and that delaying depends on case of creating script, for example if it is a cloning of entity with script and children scripts, or it is an initial initialisation.

So I will test many cases next week, and will let you know about impact of this :)

**Comment by aidinabedi** [comment]
I've change the PR to use the alternative solution I proposed, i.e. just changing this line:
- [`attributes: args.attributes || `**_`null`_**](https://github.com/playcanvas/engine/blob/fac2cd95bfa6dd7c43c4a917827880ed69470b58/src/framework/components/script/component.js#L321) -> [`attributes: args.attributes || `**_`{}`_**](https://github.com/playcanvas/engine/pull/712/files)

**Comment by aidinabedi** [comment]
I'm closing this PR as it is no longer a priority for us.

**Pull request closed without merging**
