### PR TITLE
Update to reflect that the Animation component's assets can be assets or asset ids

### PR DESCRIPTION
**Pull request by TheJonRobinson**
Per the documentation, the `assets` array in the Animation component can be assets or asset ids. The current docs declare assets, but we find ids in the arrays. So, change to be either so we can get type-safe results.

NB Confirmed generated docs as working fine.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
I'm not sure why, but GH is saying "This branch is out-of-date with the base branch" and I don't seem to see a way to fix it. Also, there are a few lines of diffs in the PR that don't seem to actually represent a real change. Would you like me to just close this and make the original change in a new commit (just to be safe)?

**Comment by TheJonRobinson** [comment]
Yes, this file was an odd one - it was CRLF (Windows) format when everything else seems to be Unix.

**Comment by TheJonRobinson** [comment]
But yeh - if you want to close and redo fine by me!

**Comment by willeastcott** [comment]
OK, done. 😄 

Closing...

**Pull request closed without merging**
