### PR TITLE
Store, use and restore any existing onPreRenderLayer function

### LINKED ISSUE #7150: Outline renderer overwrites any onPreRenderLayer function on a camera
### Outline renderer overwrites any `onPreRenderLayer` function on a camera

If the camera being used to render a scene has an `onPreRenderLayer` function assigned the outliner code will overwrite that function when activated and reset it to null when de-activated. This is happening in the `frameUpdate` method. The existing function, if present, should be preserved and called as well as the outline renderer's own `onPreRenderLayer` function.

### PR DESCRIPTION
**Pull request by MAG-ME**
Fixes #7150

This change fixes the reported issue by
- Storing any existing onPreRenderLayer function
- Calling that function as well as performing the function provided by the outliner
- Restoring the old function when the outliner is deactivated

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by mvaligursky** [comment]
yep I agree with @Maksims here completely.

**Comment by MAG-ME** [comment]
While I cannot disagree about with the comment about only having a single callback being the real issue here that would be a breaking change so how do we solve this issue?

**Comment by mvaligursky** [comment]
Let me add events in addition to existing callbacks over the next few days. This way people that depend on callbacks can keep using them. And we'll also have events, and switch internal code / scripts to use those.

**Comment by MAG-ME** [comment]
Thank you @mvaligursky, that would be much appreciated.

**Pull request closed without merging**
