### PR TITLE
Added examples to the HTTP API docs

### PR DESCRIPTION
**Pull request by yaustar**
Fixes https://forum.playcanvas.com/t/help-with-http-post-request/17400

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Review by willeastcott — APPROVED** [review]
Approving although obviously there's a bunch of lint errors ATM.

**Comment by Maksims** [comment]
Would be good to improve docs on `retry` behvaiour, for example, will it retry when 404 status returned, or only for a specific status codes?

**Comment by yaustar** [comment]
Hmm... looks like it's a pretty custom list for success.

```
_onReadyStateChange(method, url, options, xhr) {
        if (xhr.readyState === 4) {
            switch (xhr.status) {
                case 0: {
                    // If status code 0, it is assumed that the browser has cancelled the request

                    // Add support for running Chrome browsers in 'allow-file-access-from-file'
                    // This is to allow for specialised programs and libraries such as CefSharp
                    // which embed Chromium in the native app.
                    if (xhr.responseURL && xhr.responseURL.startsWith('file:///')) {
                        // Assume that any file loaded from disk is fine
                        this._onSuccess(method, url, options, xhr);
                    } else {
                        this._onError(method, url, options, xhr);
                    }
                    break;
                }
                case 200:
                case 201:
                case 206:
                case 304: {
                    this._onSuccess(method, url, options, xhr);
                    break;
                }
                default: {
                    this._onError(method, url, options, xhr);
                    break;
                }
            }
        }
    }
```

**Comment by yaustar** [comment]
I'm going to merge as is as there's a bigger question on what status code should be considered as 'succeeded' 🤔

**Pull request merged**
