### PR TITLE
build(perf): reduce build times

### PR DESCRIPTION
**Pull request by epreston**
Reduce build times by replacing a number of rollup plugins with rollup/esbuild.

- introduce `rollup-plugin-esbuild` plugin
- update build scripts to produce required outputs.
- Remove unused plugins
- consolidate build commands

Addresses #5751 

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by epreston** [comment]
## First pass

Build Timings:
- github build: 23 reduced to 8 seconds 
- desktop build: 9 seconds to 2.5 seconds

Tests:
- passing

Commands:
- working

Plugins:
- more to remove, jscc, strip etc
- transform order not optimal

Code standard:
- not configured = es2017
- comments included, configure to be stripped where required
- minification not tuned
- sourcemaps should be hires (word boundary resolution, not char boundary)

Perf Report (playcanvas.js)
- build transform is now 151 ms
- treeshake time high
- command `rollup --perf -c --environment target:release`

```
> rollup --perf -c --environment target:release

Building PlayCanvas Engine v1.67.0-dev revision 8cd24a15b

src/index.js → build/playcanvas.js...
created build/playcanvas.js in 2.6s
# BUILD: 2370ms, 276 MB / 312 MB
## initialize: 0ms, 11.1 kB / 35.8 MB
- plugin 2 (engineLayerImportValidation) - buildStart: 0ms, 2.4 kB / 35.8 MB
- plugin 4 (esbuild) - buildStart: 0ms, 936 B / 35.8 MB
## generate module graph: 1525ms, 405 MB / 440 MB
- plugin 2 (engineLayerImportValidation) - resolveId: 3ms, 707 kB / 440 MB
- plugin 4 (esbuild) - resolveId: 75ms, 4.22 MB / 440 MB
- plugin 6 (stdin) - resolveId: 0ms, 736 B / 35.8 MB
- plugin 0 (jscc) - load: 18ms, 2.55 MB / 437 MB
- plugin 1 (shaderChunks) - transform: 18ms, 5.89 MB / 440 MB
- plugin 3 (strip) - transform: 239ms, 39.4 MB / 440 MB
- plugin 4 (esbuild) - transform: 151ms, -3.54 MB / 440 MB
- plugin 5 (spacesToTabs) - transform: 23ms, 21 MB / 440 MB
generate ast: 282ms, 301 MB / 440 MB
analyze ast: 339ms, 206 MB / 440 MB
## sort and bind modules: 56ms, 10.7 MB / 451 MB
## mark included statements: 789ms, -139 MB / 312 MB
treeshaking pass 1: 135ms, -172 MB / 280 MB
treeshaking pass 2: 234ms, 11.1 MB / 291 MB
treeshaking pass 3: 100ms, 15.1 MB / 306 MB
treeshaking pass 4: 51ms, 4.41 MB / 310 MB
treeshaking pass 5: 34ms, -3.74 MB / 306 MB
treeshaking pass 6: 27ms, 1.74 MB / 308 MB
treeshaking pass 7: 25ms, 208 kB / 308 MB
treeshaking pass 8: 25ms, -903 kB / 307 MB
treeshaking pass 9: 25ms, -2.42 MB / 305 MB
treeshaking pass 10: 24ms, -2.42 MB / 303 MB
treeshaking pass 11: 22ms, -3.94 MB / 299 MB
treeshaking pass 12: 21ms, 11.6 MB / 310 MB
treeshaking pass 13: 22ms, -4.96 MB / 305 MB
treeshaking pass 14: 22ms, -5.06 MB / 300 MB
treeshaking pass 15: 22ms, 11.4 MB / 312 MB
# GENERATE: 234ms, 42 MB / 354 MB
## initialize render: 0ms, 3.76 kB / 312 MB
## generate chunks: 10ms, -9.33 MB / 303 MB
optimize chunks: 0ms, 94.6 kB / 300 MB
## render chunks: 214ms, 32.1 MB / 335 MB
## transform chunks: 10ms, 19.2 MB / 354 MB
- plugin 4 (esbuild) - renderChunk: 0ms, 552 B / 347 MB
## generate bundle: 0ms, 1.94 kB / 354 MB
# WRITE: 11ms, -8.43 MB / 346 MB
```

**Comment by willeastcott** [comment]
Well, this is looking promising so far. 😄

**Comment by Maksims** [comment]
Do you have size comparisons also?
And if there is any difference between JS features used in old builds and new builds.

**Comment by kungfooman** [comment]
> And if there is any difference between JS features used in old builds and new builds.

Since Babel is kicked out and it was used for compatibility, it pretty much means:
 - `for-of` protocol is no longer transpiled into ES5 Babel iterator code
 - `class` constructs are no longer transpiled into `function`'s
 - template literals remain template literals
 - something more? IDK, pretty much everything Babel does for targetting IE11

Last time I checked `esbuild` it didn't support ES5 (that's why I went for Parcel), that probably didn't change either.

Size difference is 600kb (current playcanvas.js is 2.7 MB, PR is 3.3 MB), for some reason `esbuild` is introducing lots of ugly `publicField` statements:

image

Maybe that can be configured away?

So this pretty much kills ES5 and personally I'm fine with that, but as always, YMMV.

**Comment by epreston** [comment]
@Maksims I will prepare that as part of the plan in the linked issue: #5751.  Old builds are defined as "whatever IE 11 can support" which is too low.  It's a good time for device support discussion to get some feedback and review. #5697  Bit early to measure that, I've got specific goals for each pass.

To get the notable reductions in size and perf improvements on the single file releases, the project needs to adopt language features from the last 10 years.  Right now, we'll only see the benefits of correctly configuring terser, sourcemap resolution on word boundary, "\n" replacement, "top level var".

If you want to get a feel for it quickly by changing the support target in the template project linked in the issue.  You can plugin values into the support target (as discussed in the analysis) go from 1.4mb, 808kb, to lower still.

If you got a public project you want me to look at, create and issue on it and link me.  Happy to help.

**Comment by epreston** [comment]
@kungfooman please refrain from spamming.  You can read the content above noting what is not done and see that this in draft.

**Comment by epreston** [comment]
@willeastcott I'll finish this offline.

**Comment by marklundin** [comment]
Hey @epreston, just following up on this. Great work btw 👏 Was there any specific reason why you closed this PR?

**Comment by epreston** [comment]
@marklundin Yes, clearer "work notes" while drafting this PR.  
I closed this draft PR and completed it offline.

**Pull request closed without merging**
