### PR TITLE
Support for glTF scenes, cameras and lights

### LINKED ISSUE #2062: Support for glTF cameras
### Description
Currently, when loading a glTF which contains one or more camera objects ([as supported in the specification](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#cameras)) no actual camera is added to the scene. This is an important standard glTF 2.0 feature that we need (and is supported by most other major WebGL libraries).
​
### Steps to reproduce
1. Open project https://playcanvas.com/project/684225/overview/gltf-cameras-test
2. Open scene “CameraTest” and launch it
​
### What I expect to see and what I saw instead
Screenshot 2020-05-07 at 11 16 35

### LINKED ISSUE #2063: Load glTF scenes as entity hierarchies
Currently, glTF scenes are loaded as `pc.Model` objects. A `pc.Model` has a hierarchy made up of `pc.GraphNode` objects. A `pc.Entity` is a sub-class of `pc.GraphNode`, the main difference being that an entity can have components but a graph node cannot. Until we make this change, we cannot fix issues #2061 and #2062. Note that this issue has significant overlap with #1035.

In the Editor, this would mean importing 3D scenes as template assets rather than model assets.

### PR DESCRIPTION
**Pull request by godiagonal**
Related to #2063
Fixes #2062 #2061 

These are customizations of the GLB parser that we (Animech) have had to make to satisfy the requirements of one of our ongoing projects. I noticed there are other PRs related to #2063 that might be more in line with how you want the parser to work, but I thought I would share our implementation anyway since it has been working well in our use case.

## Features
* Support for scenes
  * Adds props `pc.ContainerResource.scenes`, `pc.ContainerResource.scene` and `pc.ContainerResource.nodes`.
  * Scenes and nodes are exported as `pc.Entity` hierarchies.
  * The `scenes` and `scene` props of the glTF are used to create the exported scenes.
  * Can be processed using asset option callbacks `preprocess`, `process` and `postprocess`.
* Models are created per glTF `mesh` instead of just one per glTF.
  * `pc.ModelComponent` is automatically added to all nodes referencing a mesh.
  * Adds `pc.ContainerResource.models`, a list of `pc.Model` assets per glTF mesh. Useful if using glTF extensions that 
reference meshes.
  * Removes `pc.ContainerResource.scenes.model`.
* Support for cameras
  * `pc.CameraComponent` is automatically added to all nodes referencing a camera.
  * Adds `pc.ContainerResource.cameras`, a list of all `pc.CameraComponent` instances. Does not match index of the glTF `cameras` array.
  * Can be processed using asset option callbacks `preprocess`, `process` and `postprocess`.
* Support for `KHR_lights_punctual`
  * `pc.LightComponent` is automatically added to all nodes with extension `KHR_lights_punctual`.
  * Adds `pc.ContainerResource.lights`, a list of all `pc.LightComponent` instances. Does not match index of the glTF `lights` array.
  * Can be processed using asset option callbacks `preprocess`, `process` and `postprocess`.
* Animations grouped by node
  * Adds `pc.ContainerResource.animationIndicesByNode`, a mapping of animation indices to nodes. This can be used to add an animation component of choice (`pc.AnimComponent` or `pc.AnimationComponent`) to nodes that should be animated. The animations must be assigned to the referenced nodes to work, since the animation tracks use relative paths to target child nodes.
* Updates JSDoc for `pc.ContainerResource`.

## Rationale
Exporting scenes rather than a model better correspond to the glTF 2.0 spec which treats glTF as a scene format. It makes it possible to populate the scene with models, cameras, lights etc in the parser.

## Other changes
For the new GLB parser implementation to work I also had to make the following changes.
* Updated `pc.Model.clone()` so that references to external bones (nodes outside the internal model graph) of skin instances are kept in the cloned model.

## Test instructions
Launch [this project](https://playcanvas.com/editor/scene/976797) using a custom build of the engine from this branch. Use [this launch url](https://launch.playcanvas.com/976797?debug=true&use_local_engine=https://launch.playcanvas.com/api/assets/files/playcanvas.js?id=34573773&branchId=a1fc2544-c925-470b-b5c8-d17e5cd4553c).

The project showcases a glTF asset containing a single scene with animations, cameras and lights being loaded by this version of the GLB parser.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by mvaligursky** [comment]
Thanks, we definitely were keen to add this and more. We have multiple changes in flight in the glb-parser related to this as well, so this might take a while to get merged in / worked on.

**Comment by willeastcott** [comment]
@mvaligursky With the progress we've made importing models as asset templates, are we now in a position to import cameras and lights?

**Comment by mvaligursky** [comment]
We can import cameras and lights from fbx files in the editor - which gets converted into a glb file for meshes, and a template file for hierarchy with render / light / camera components.
But once the render component goes public, we should still consider updating this PR to use render component (instead of model component) and use it to allow us to load hierarchies of entities with cameras and lights directly in the engine.

**Comment by willeastcott** [comment]
Yeah, I'm thinking more of creating `CameraComponent`s and `LightComponent`s in asset templates on import. If that's the route we're going (and presumably we can get there soon), can this PR be closed?

**Comment by Maksims** [comment]
This definitely needs Editor work with UX to define import settings, as there will be cases where creating lights or cameras won't be desirable, and vice versa.

**Comment by mvaligursky** [comment]
Current implementation for fbx-> glb+ templates imports everything. Import options is discussed a lot and we'd like to implement it for many reasons. But in this specific case, templates kind of handle it for us. If you for example import fbx, it generates gbl with geometry only, and hierarchy with components create a template. So you can place it into the scene, have Entity hierarchy with components referencing meshes, lights, cameras ... If you don't want some / all lights, you simply delete them from the template. When you drag & drop newly exported fbx with say changes to meshes, it won't bring back your lights, as template has 'remove these entities with lights' overrides on them. So the end result is what you want.

But that does not decrease the need for import settings in the future for many other reasons.

**Comment by mvaligursky** [comment]
@willeastcott - we have good new "fbx -> gbl + template" pipeline (not released to public yet), for which this PR is not needed.

But it'd be still useful to allow external glb files to be loaded (they will not have template created), and be able to use cameras and lights, and even render component. So this PR would be useful for that, even thought a large part of it will not be needed anymore or will need to change. I'd like to keep it for reference of light / camera support from glb though.

**Comment by mvaligursky** [comment]
Closing this, as the engine implementation of these has already been done now (based on this PR, thanks so much for making it @godiagonal), or any remaining work has been captured in the issues.

**Pull request closed without merging**
