### PR TITLE
Fixed bug where new sound instances aren't kept

### PR DESCRIPTION
**Pull request by yaustar**
When `sound.positional` is set by the developer, the new instances created are no longer kept in slot.instances. This means that the sound is audible but the slot.isPlaying property is false because it has no instances and the developer can no longer stop the sound.

Reproduced in: https://playcanvas.com/project/747427/overview/sound-positional-issues

Open up dev console in the browser

Press 1 to play the sound, 4 to toggle positional property.

Notice that isPlaying is false in the console (press 3) and that pressing 2 to stop the sound doesn't stop the sound.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by vkalpias** [comment]
Let me know if I'm wrong but it seems to me that the old code should work if you just reverse the loop? Which might avoid creating a new array? Although it probably will still splice instances from the old array and then resize it to the old size again so not sure if it's better.

**Comment by yaustar** [comment]
> Let me know if I'm wrong but it seems to me that the old code should work if you just reverse the loop? Which might avoid creating a new array? Although it probably will still splice instances from the old array and then resize it to the old size again so not sure if it's better.

I can give it a try but I think we get the same issue as on stop, the instance is spliced out of the array. The test above is with one sound instance so reversing and going forward would be the same thing in this case :)

**Comment by yaustar** [comment]
Oh, I did think about pushing the new instances to the end of the array and doing something to ensure that only the old ones are removed but it didn't seem as clear for something that is probably done rarely for the sake of not allocating a new array.

**Comment by yaustar** [comment]
@vkalpias I've got an idea on how to avoid creating a new array if you would like me to implement that instead? It will make the logic a bit harder to follow though 😅

**Comment by yaustar** [comment]
I've updated the PR to avoid the array allocation as Vaios mentioned above.

**Review by vkalpias — APPROVED** [review]

**Pull request merged**
