### PR TITLE
Engine is using Debug class to log warnings / errors to avoid #ifdef _DEBUG

### PR DESCRIPTION
**Pull request by mvaligursky**
replacing calls inside _DEBUG by static functions of the Debug class

### CODE REVIEW

**Comment by willeastcott** [comment]
Just wondering. Why have the indirection via a `Debug` API when you can use the Rollup strip plugin to strip console.* functions directly?

**Comment by willeastcott** [comment]
Is it reasonable to imagine a world where a production build PlayCanvas app would never output to the console? Read the first paragraph here:

https://eslint.org/docs/rules/no-console

**Comment by mvaligursky** [comment]
Yep, that's possible.

My hope is that at some point we send all console logs using some logging class, so we can surface them in some Debug log panel inside the Editor.

But perhaps we should have a discussion about how to best approach this.

**Comment by willeastcott** [comment]
Fair enough. Approving for now then.

**Review by willeastcott — APPROVED** [review]

**Pull request merged**
