### PR TITLE
Make version logging at startup optional

### PR DESCRIPTION
**Pull request by fiso**
See title

Fixes #

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).
Yes!

### CODE REVIEW

**Comment by willeastcott** [comment]
@yaustar No, I don't think it's needed due to the MIT license. But I personally do find it incredibly useful when checking if new WebGL apps I find are PlayCanvas. I'm kinda open to this....I'll give it some thought.

**Comment by fiso** [comment]
> @yaustar No, I don't think it's needed due to the MIT license. But I personally do find it incredibly useful when checking if new WebGL apps I find are PlayCanvas. And to check what version engine they're on (since then I can see quickly if an issue is already fixed in a newer engine release). But I'm kinda open to this....I'll give it some thought.

If that's an important use-case, you could solve that by exposing some object on the window which can be checked by the curious. Forcing console logging in a production build is something I would say should be avoided.

For reference, here is the long-running discussion from when the author of Three.js after a lot of back and forth decided to remove the mandatory logging done by that library: https://github.com/mrdoob/three.js/pull/5835

**Comment by LeXXik** [comment]
As a consumer, I do like that version output in the console. I would prefer it to stay there and perhaps add an explicit option to turn it off for those who needs it to be off for their reasons.

**Comment by fiso** [comment]
> As a consumer, I do like that version output in the console. I would prefer it to stay there and perhaps add an explicit option to turn it off for those who needs it to be off for their reasons.

Yeah and this PR does exactly that. Out of the box nothing changes, but _if_ you have a preference for a clean console this gives you a nice way to disable the informational log message without resorting to money patching.

**Comment by yaustar** [comment]
Closing this in favour of https://github.com/playcanvas/engine/pull/3508

**Pull request closed without merging**
