### PR TITLE
Orient glb quaterion keys correctly

### LINKED ISSUE #1964: AnimatedTriangle.gltf does not rotate correctly
### Description

I used the PlayCanvas built-in glTF Loader to display a [glTF model](https://github.com/cx20/gltf-test/tree/master/tutorialModels/AnimatedTriangle/glTF).
However, the model does not seem to rotate correctly.
Previously, when displaying the glTF model using [playcanvas-gltf](https://github.com/playcanvas/playcanvas-gltf), the rotation was [correct](https://rawcdn.githack.com/cx20/gltf-test/dfd110cf9e0f8e3e49033b5b1f9f59c7a2b7424e/examples/playcanvas/index.html?category=tutorialModels&model=AnimatedTriangle&scale=1&type=glTF).

### Steps to Reproduce

1. Display the glTF model with playcanvas-gltf
[PlayCnavav1.26.0-dev + playcanvas-gltf + AnimatedTriangle.gtf result:](https://rawcdn.githack.com/cx20/gltf-test/dfd110cf9e0f8e3e49033b5b1f9f59c7a2b7424e/examples/playcanvas/index.html?category=tutorialModels&model=AnimatedTriangle&scale=1&type=glTF)
The model is rotated correctly.

2. Display the glTF model with PlayCanvas' built-in glTF Loader.
[PlayCanvas v1.27.0-dev + AnimatedTriangle.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/d1d9990e2406792499a9258af1b46564d873740f/examples/playcanvas/index.html?category=tutorialModels&model=AnimatedTriangle&scale=1&type=glTF)
PlayCanvas_AnimatedTriangle_20200404_001
The rotation is not correct.
**Expected behavior**
expected_screenshot

This model is expected to rotate seamlessly.
https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_006_SimpleAnimation.md

### PR DESCRIPTION
**Pull request by slimbuck**
Fixes #1964

Quaternions encode rotations through 720 degrees (not just 360) and so quaternion q and -q face the same direction.

When interpolating between two quaternion animation keys you almost always want to take the shortest path between them. A simple dot product between two quaternions indicates whether they fall in the same winding or not.

This code iterates over the GLB quaternions and ensures consecutive keys fall in the same winding.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
I was wondering....I don't recall the original glTF loader having this problem with animation. And it doesn't process the quaternions as you are here:

https://github.com/playcanvas/playcanvas-gltf/blob/master/src/playcanvas-gltf.js#L101

What's the deal with that?

**Comment by slimbuck** [comment]
The engine performs this job every time quaternion slerp is called, see https://github.com/playcanvas/engine/blob/master/src/math/quat.js#L613.

The GLB animation code doesn't slerp quaternions, but interpolates them linearly instead (just like all the other data). This means we must perform the flip ahead of time.

**Comment by mvaligursky** [comment]
should slerp not be used for quaternion interpolation? linear interpolation gives you different results

**Comment by slimbuck** [comment]
Interesting... the glb spec actually says to use slerp for quaternions when performing LINEAR interpolation (which I hadn't seen before) even though this isn't possible with CUBIC interpolation.

I've done a bit of research into slerp vs lerp and though slerp is usually implemented, the difference compared to lerp is mostly small (especially for sampled data like ours). See https://caseymuratori.com/blog_0002 and http://number-none.com/product/Hacking%20Quaternions/.

It might worth reevaluating this to determine exactly the error and perhaps even offer the user the option of slerp vs lerp. I think in probably 95% of cases users won't notice the difference and would appreciate the speed advantage.

**Comment by mvaligursky** [comment]
The error would be small for sampled data (say at 10fps) .. but is that what comes from glb, or are those actual sparse keyframes?

**Comment by slimbuck** [comment]
Our GLB converter currently samples TRS at 10fps, but I would like to implement exporting the sparse cubic keys asap! (and remember cubic keys can't be slerped...).

**Pull request merged**
