### PR TITLE
Exposed Scene.sky properties

### PR DESCRIPTION
**Pull request by mvaligursky**
Scene.sky should have been public, and this PR fixes it.

Screenshot 2024-10-16 at 09 47 47

Screenshot 2024-10-16 at 09 48 01
Screenshot 2024-10-16 at 09 48 08

### CODE REVIEW

**Comment by willeastcott** [comment]
What do we do about:

* https://api.playcanvas.com/classes/Engine.Scene.html#setSkybox
* https://api.playcanvas.com/classes/Engine.Scene.html#skybox
* https://api.playcanvas.com/classes/Engine.Scene.html#skyboxIntensity
* https://api.playcanvas.com/classes/Engine.Scene.html#skyboxLuminance
* https://api.playcanvas.com/classes/Engine.Scene.html#skyboxMip
* https://api.playcanvas.com/classes/Engine.Scene.html#skyboxRotation

**Comment by mvaligursky** [comment]
> What do we do about:

Leave it for another PR.

**Comment by mvaligursky** [comment]
@willeastcott any objections to merge this?

**Review by willeastcott — APPROVED** [review]
OK, go for it, but sky API needs a concerted clean up! 🧹

**Pull request merged**
