### PR TITLE
HDR physically based bloom + render pass examples

### PR DESCRIPTION
**Pull request by mvaligursky**
Fixes: https://github.com/playcanvas/engine/issues/5187
Related Issue: https://github.com/playcanvas/engine/issues/5687

## New Engine API (private for now, while in preview)
- **CameraComponent.renderPasses** - an array of render passes the camera will use to render, instead of its default rendering.
- **RenderPassShaderQuad** - new render pass, a base class for render passes that render quad using a shader.

## Extras
Multiple render passes in `/extras`, used to implement HDR Bloom:
- RenderPassUpscale/Downscale - quad based passes, used to upscale and downscale the image
- RenderPassBloom - render pass using upscaling and downscaling to generate bloom texture
- RenderPassComposite - a render pass compositing the scene texture with bloom texture. This will be expanded by multiple post-effects as part of the same shader / render pass: color-corrections, distortion, screen-texture and many others.

## Examples
Two examples:
- RenderPassExample: simple example showing a custom render pass (tint) and how to use it to tint the rendered scene
Screenshot 2023-11-20 at 16 05 25

- PostprocessingExample: example using new render passes from `/extras` to set up a scene with HDR bloom. Control over render passes allows user to render 3d scene to lower resolution HDR texture, apply bloom and then render UI on top of it in full resolution.
Screenshot 2023-11-20 at 16 04 52

### CODE REVIEW

**Review by slimbuck — APPROVED** [review]

**Comment by MAG-AdrianMeredith** [comment]
Very nice, render pass implementation over post effects looks nice.  Look forward to comparing it to ours.

**Comment by mvaligursky** [comment]
Yep, the render passes are a really nice way to put this together.
If you at some point write another bloom implementation using passes, we can easily add that to extras too, no problem with that.

**Comment by MAG-AdrianMeredith** [comment]
@mvaligursky Have you tried this with a directional light present?  I'm getting errors here 
image
the shadowCamera.renderTarget is undefined.   it works otherwise and could just be me but its worth checking

**Comment by MAG-AdrianMeredith** [comment]
image

**Pull request merged**
