### PR TITLE
Publish npm package for the browser

### LINKED ISSUE #932: Make available on npm
Would like to to be able to require the engine as a module.

### PR DESCRIPTION
**Pull request by aidinabedi**
Fixes #932

Currently, all major WebGL game engines (except PlayCanvas) publish official npm packages, including:
- [three.js](https://www.npmjs.com/package/three) (180K+ weekly downloads)
- [babylon.js](https://www.npmjs.com/package/babylonjs) (5K+ weekly downloads)

<br/>

This PR puts the finishing touches, so PlayCanvas can be published as an official npm package. The PR has been used to publish [an unofficial package](https://www.npmjs.com/package/@aidinabedi/playcanvas) which can be tested by following a few steps:
1. Clone repo [playcanvas-npm-test](https://github.com/aidinabedi/playcanvas-npm-test)
2. Run `npm install`
3. Run `npm run start`
4. Open [localhost:9966](http://localhost:9966/)

<br/>

To publish an official npm package follow some simple steps:
1. Merge PR branch [feature/publish-npm-package](https://github.com/aidinabedi/playcanvas-engine/tree/feature/publish-npm-package) locally into [playcanvas/engine](https://github.com/playcanvas/engine) `master`
2. Run `npm run build`
3. Run `npm run tsd`
4. Run `npm login` and enter your username, password, and email address
5. Run `npm publish`
6. Open [npmjs.com/package/playcanvas](https://www.npmjs.com/package/playcanvas)

_NOTE: you can't replace an already published version. To publish test versions simply append a prefix (like `-test1`) to the version field in `package.json`._
<br/>

PR changes:
- Improve `.npmignore` (ignore everything but `LICENSE`, `README.md`, `VERSION`, `build/output/`, `extras/`, `package.json`, and `package-lock.json`).
- Improve keywords in `package.json`.
- Add `index.d.ts` to wrap TypeScript declarations like a module (necessary for an npm package).
- Remove `jsdom` dependency since it's NOT needed for running PlayCanvas in the browser and just increases browserify's output with a whopping 6MB. Adding support for non-browser platforms (i.e. node) is a separate PR (#1579) and not necessary for publishing packages.

<br/>

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
I've been thinking that we're just about ready to do this officially! Yay!

So, what do you think we should name the package? Options are:

* playcanvas
* @playcanvas/engine
* @playcanvas/playcanvas
* @playcanvas/playcanvas.js

Note that I put the JSDoc template under @playcanvas as @playcanvas/jsdoc-template.
And I'm planning to move playcanvas-esline-config to @playcanvas/eslint-config.

**Comment by aidinabedi** [comment]
Me too. Been looking forward to this 😄

I would go with just `playcanvas` for the engine. It's more official and professional IMHO. And you don't want some 3rd-party to use that package name.

Three.js uses just `three` but babylon has actually both [packages named `babylonjs-*`](https://doc.babylonjs.com/features/npm_support#available-packages) and [es6 packages named `@babylonjs/*`](https://doc.babylonjs.com/features/npm_support#es6).

I would suggest using `@playcanvas/*` for non-engine packages.

**Comment by willeastcott** [comment]
Quick question: why can't the package.json just have:

    types: "build/output/playcanvas.d.ts"

?

**Comment by aidinabedi** [comment]
There are two use-cases for the TypeScript declarations as I see it.
1. When adding `playcanvas-latest.js` to html and accessing it as a global namespace (i.e. `pc`).
2. When adding PlayCanvas's npm package and accessing it as a module, i.e.:
   - JavaScript: `var pc = require("playcanvas");`
   - TypeScript: [`import * as pc from "playcanvas";`](https://github.com/aidinabedi/playcanvas-npm-test/blob/master/index.ts#L1)

The current output of `playcanvas.d.ts` can only be directly used in the first use-case. Since it only `declares` the types, it doesn't export any types, which a module should. So what [`index.d.ts`](https://github.com/playcanvas/engine/blob/master/index.d.ts) does is it imports the declared types and exports it just like a module.

`package.json` could reference `playcanvas.d.ts` directly if it had an `export` statement, something like `export = pc;`.

**Comment by willeastcott** [comment]
Could we add export = pc; as a post build step of the tsd script in the package.json?

**Comment by aidinabedi** [comment]
Of course. We could also change the jsdoc command in `package.json` like so:
```
jsdoc -c conf-tsd.json && echo export = pc >> build/output/playcanvas.d.ts
```
However, in the above case we would have to drop the semicolon `;` (since it behaves differently in the command-line depending on platform) and overall such a post-build step feels a little too hackish IMHO. In my mind, `index.d.ts` is a sufficient short term solution, just to get the package out. In the "long" run (hopefully beginning of next month), I would love to improve this directly in `tsd-jsdoc`. Maybe add a feature that would allow us to insert arbitrary TypeScript (i.e. `export = pc;`) to the final `d.ts` output via jsdoc comments.

**Comment by willeastcott** [comment]
Ooooh, that's a great idea. 👍

**Pull request merged**
