### PR TITLE
animated skin batchings updated

### PR DESCRIPTION
**Pull request by Glidias**
Feature to add batching support for animated skin models.

reference test
https://playcanvas.com/editor/code/556581?tabs=12567268

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by Glidias** [comment]
hold off this for a while. after some testing, i noticed my floating sprite with custom vertex-shader + batch sprite targetboard model should appear as well. But somehow,  it doesn't. Need to ensure both batch animated skinned model changes and my batch custom vertex-shader sprites are working as well.
The required look:
image

**Comment by thisredone** [comment]
This would be cool to have

**Comment by willeastcott** [comment]
It certainly would be cool to batch skinned mesh instances. The batching code was just refactored by @mvaligursky [here](https://github.com/playcanvas/engine/pull/2041). That might make it difficult to merge this. But perhaps we can rewrite and integrate a new implementation. But I'll leave it to @mvaligursky to oversee that. 😄

**Comment by sakidev** [comment]
This is a must to achieve good performance on low-end devices for *any* complex game.

**Pull request closed without merging**
