### PR TITLE
AnimStateGraph: Add JSDoc types

### PR DESCRIPTION
**Pull request by kungfooman**
Currently there are no types in `playcanvas.d.ts`:

image

This PR implements all the types the class `AnimStateGraph` accepts:

image

This enables Intellisense for e.g. PC Viewer:

image

Fixing ESLint is not so easy, because I am running into some VSCode/TypeScript issue or so: https://github.com/eslint/eslint/discussions/14235

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by Maksims** [comment]
How does this affects docs generation?
Also, this is something we haven't done before, and looks like specifically for TypeScript, not for everyone else.

**Comment by kungfooman** [comment]
> How does this affects docs generation?

Good point, it currently produces a 404, which should be fixed to produce a proper object description (maybe inline):

image

> Also, this is something we haven't done before, and looks like specifically for TypeScript, not for everyone else.

I mainly did this for `playcanvas-viewer`, which is written in TypeScript, to get rid of `// @ts-ignore` cases. It also helps JavaScript developers in Visual Studio Code or any other editor that supports JavaScript IntelliSense.

**Comment by vmwxiong** [comment]
> How does this affects docs generation?
> Also, this is something we haven't done before, and looks like specifically for TypeScript, not for everyone else.

Eavesdropping in, but I'd love to see support for explicit TS definition contributions somehow. Been doing a bunch of work to get proper types for some things, but not sure how I could possibly contribute the work to the project at all: https://gist.github.com/vmwxiong/eabc60834b32801f5a38de99f4acad80

**Comment by kungfooman** [comment]
> Eavesdropping in, but I'd love to see support for explicit TS definition contributions somehow. 

The generated `playcanvas.d.ts` is kinda as "proper" as it gets, only that generating it through `JSDoc` feels a bit convoluted. The custom doc generation from it doesn't make it more straight forward either, like fixing something in this repo needs another fix in https://github.com/playcanvas/playcanvas-jsdoc-template e.g.

For more "advanced" typing like yours it would make sense to append it directly to `playcanvas.d.ts` after its generation, so it's shared for anyone who installed PlayCanvas through `npm`. Putting extra typing clues in too many places could make it overly confusing though, so one should try to make use of JSDoc whenever possible (and keep `playcanvas-jsdoc-template` synched to display types in an informative/easy/understandable way)

**Review by hixio-mh — APPROVED** [review]
#
Reviews and change

**Comment by kungfooman** [comment]
Any is good enough, we shouldn't overcomplicate types like this.

**Comment by vmwxiong** [comment]
`any` is extremely painful to with with as it blows up attempts at building type-safe code, and you need to write and use convoluted type guards every time you want to use something typed with an `any` value.

Disappointed to see the project not moving to support type safe definitions.

**Comment by willeastcott** [comment]
@vmwxiong I think you missed this conversation: https://github.com/playcanvas/playcanvas-viewer/pull/98#issuecomment-966316720

The plan is to make `AnimStateGraph` internal. So this is no longer an issue.

You may have also noticed this week that I have submitted several issues on the repo about improving the Typescript definitions. So saying that 'the project is not moving to support type safe definitions' is not fair or accurate, IMHO. The only time it is difficult to solve typing definitions problems is when it negatively impacts the quality of the API reference manual. Otherwise, everybody is excited to be improving the quality of the typings.

**Comment by vmwxiong** [comment]
Ah, thanks for the clarification, apologies for jumping to conclusions

**Pull request closed without merging**
