### PR TITLE
SSAO engine example

### PR DESCRIPTION
**Pull request by mvaligursky**
- new example using the existing script. In the following PRs the SSAO will be converted to new render pass architecture.

enabled:
Screenshot 2024-05-23 at 10 35 47

disabled:
Screenshot 2024-05-23 at 10 35 57

### CODE REVIEW

**Review by kpal81xd — APPROVED** [review]

**Comment by LeXXik** [comment]
Is there a reason not to use the new architecture right away?

**Comment by mvaligursky** [comment]
> Is there a reason not to use the new architecture right away?

not a strong reason, apart from:
- smaller easier to review PRs
- easier to compare. before / after

I'm already working on the render pass version, but in the meantime, this can be reviewed, as it's an independent part of work.

**Comment by Maksims** [comment]
It looks like the lightmap in this art already has some AO.

**Comment by willeastcott** [comment]
> It looks like the lightmap in this art already has some AO.

Yeah, I'm not fully convinced this is the ideal model/scene to show off AO.

**Comment by mvaligursky** [comment]
Well spotted @Maksims - I disabled their AO maps now, and updated screenshot.
The asset size is now 6MB @willeastcott

**Pull request merged**
