### PR TITLE
Fix compressed texture skybox issue.

### PR DESCRIPTION
**Pull request by H1Gdev**
Use compressed texture in cubemap and not applied to  skybox.
(Use **easy texture compression**).

### CODE REVIEW

**Comment by guycalledfrank** [comment]
IMHO, compressed textures need to be flipped in advance. That's what our server pipeline does.

**Comment by Maksims** [comment]
If the PR introduces change to logic or some additional functionality, and it is not related to any existent Issue, then it is better to first make an Issue for a discussion, and there we can come up together with some good design and talk about a change in first place to ensure all things are in check.

**Comment by H1Gdev** [comment]
Hi @guycalledfrank 
Use **easy texture compression** and output flipped texture(Y axis).
So, need need to Y flip the image in the shader.

**Comment by guycalledfrank** [comment]
Flipping the texture in advance is the way to go.

**Comment by H1Gdev** [comment]
Oh...
I look forward to future support.

**Pull request closed without merging**
