### PR TITLE
Simplify pc.Light#mask and pc.Light#enabled code

### PR DESCRIPTION
**Pull request by weilichuang**
Fix light enabled

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
Interesting! It's great that you noticed this mistake in the code, @weilichuang! After looking at the code, it seems that `pc.Light#enabled` (and `pc.Light#mask`) do not need to be getters/setters. They can just be raw properties. This simplifies the code and makes it faster too. So I've changed your PR. I hope you don't mind. 😄

**Comment by willeastcott** [comment]
Just to be clear, I don't think the original change fixed any bugs, despite the code clearly being wrong.

**Comment by slimbuck** [comment]
Seems the engine references _mask in the engine (there may also be references to _enable).

See for example https://github.com/playcanvas/engine/blob/master/src/scene/forward-renderer.js#L797

**Comment by willeastcott** [comment]
Nice catch. Fixing now...

**Comment by willeastcott** [comment]
OK done. Please re-review.

**Comment by willeastcott** [comment]
Hi @weilichuang - you didn't sign the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform). In this case, it's OK, because I completely rewrote the PR. But next time, it's a good idea to sign it or we can't merge. 😄  Anyway, thanks for letting us know about the original problem

**Pull request merged**
