### PR TITLE
Fix WebGL 2.0 PCF3 shadow issue.

### PR DESCRIPTION
**Pull request by H1Gdev**
Use playcanvas-latest.js in default playcanvas project(only Camera, Light, Box, Plane), and do not display model surface correctly.

So I PR.

### CODE REVIEW

**Comment by Maksims** [comment]
There were recent changes to bias, which leads to some bias differences, which means some adjustments to bias value are required.
This change changes logic. We will update default bias value to have better results.

**Comment by guycalledfrank** [comment]
Hi, I didn't get what you're trying to accomplish. Besides, FUNC_NOTEQUAL doesn't make any sense and will break shadows in any complex scenarios.

**Comment by H1Gdev** [comment]
Thanks for response this PR.

Please fix this issue in another way.

**Comment by willeastcott** [comment]
I believe @Maksims  has now updated the default shadow bias when creating new projects. You may have to tweak the bias of existing projects.

**Comment by H1Gdev** [comment]
Hi, @willeastcott.
Thank you for teach me.
Change shadowBias and normalOffsetBias the same values as current new project from Editor, and fixed this issue.

**Pull request closed without merging**
