### PR TITLE
Immediate render/gizmos

### PR DESCRIPTION
**Pull request by guycalledfrank**
"Immediate" rendering functions that will draw something only in this frame:

    // Draw meshInstance at this frame
    app.renderMeshInstance(meshInstance)

    // Draw mesh at this frame
    app.renderMesh(mesh, material, matrix)

    // Draw quad of size [-0.5, 0.5] at this frame
    // layer is optional
    app.renderQuad(matrix, material, layer)

    // Draw straight line at this frame
    // Possible usage:
    // renderLine(start, end, color)
    // renderLine(start, end, color, endColor)
    // renderLine(start, end, color, onTop)
    // renderLine(start, end, color, endColor, onTop)
    app.renderLine(start, end, color, arg3, arg4)

    // Draw array of straight lines at this frame
    // color can be const or array
    // both arrays must have equal length and be divisible by 2
    // onTop is optional
    app.renderLines(position, color, onTop)

    // Draw lines forming a transformed unit-sized cube at this frame
    // onTop is optional
    app.renderWireCube(matrix, color, onTop)

Also:
- Fixed BasicMaterial.clone
- BasicMaterial can be vertexColored (it was half-done before)
- Added "preRender" event that fires before render

### CODE REVIEW

**Comment by Maksims** [comment]
What `layer` can be? Is it same as `onTop`? And if there is a way to have post render for meshes too?
To have some stuff rendered on top of basic scene, but still being sorted with same layer stuff.
What is the difference between `renderMeshInstance` and `renderMesh`?

**Comment by guycalledfrank** [comment]
layer is pc.LAYER_* enum

**Comment by willeastcott** [comment]
For uniformity, can't all these functions take a layer argument?

**Comment by guycalledfrank** [comment]
For lines, onTop doesn't only mean layer, but also disabling ztest

**Comment by Maksims** [comment]
Does that means they will be always on top of everything, and there is no way to draw line on specific layer overlapping with that layers zbuffer?

**Comment by guycalledfrank** [comment]
Drawing overlapping lines, while not intersecting with zbuffer? This would require clearing zbuffer before drawing, which is not the cheapest thing to do. I'm not convinced we should do it. Clear is issued in editor anyway, so adding another one will clear it twice. And it's not issued in game, so we can't rely on editor's clear. We can branch (if editor, else game), but what if user adds his own clear by code, and then he doesn't need 2 clears again, when lines are drawn... complicated.

**Pull request merged**
