### PR TITLE
Fix GLB url assumption bug in glTF loader

### LINKED ISSUE #1970: glTF loader assumes GLB url must end with .glb
### Description
PlayCanvas's built-in glTF asset loader can't recognize a `GLB` file if the url doesn't end with `.glb`. Currently, it can't for example handle URLs that end with query parameters (`?foo=bar`) or hash anchors (`#foobar`).

### Steps to Reproduce
1. Open project: https://playcanvas.com/project/675955/overview/gltf-json-vs-binary-test
2. Open scene "Untitled" and launch it.

### What I expected to see
image

### What I see instead
image

### PR DESCRIPTION
**Pull request by aidinabedi**
Fixes #1970

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by slimbuck** [comment]
Instead of testing the binary header this way, I would rather fix ContainerHandler.load() to pass in the correct filename (excluding the query parameters). The reason is container may support more than GLB format in future (thus the wildly generic name) and having a correct filename is the best approach there. Also, I prefer the stronger test of 'this GLB is invalid' to the weaker 'this is not a GLB file', if that makes sense.

**Comment by aidinabedi** [comment]
@slimbuck Thank you for the feedback.

Please note that using an "exotic" file extension (such as `.gltf`, `.glb` etc) isn't always an option depending on what hosting solution, REST API or even URL-schema you have to use.

Also note that [testing the header is the main proposed way of identifying a binary glTF per specification](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#header): 
> `magic` equals `0x46546C67`. It is ASCII string `glTF`, and can be used to identify data as Binary glTF.

**Comment by slimbuck** [comment]
Hi @aidinabedi, the asset filename is specified separately from url which allows, for example loading from blobs. The rest of playcanvas uses filename extensions to determine asset types, images, models etc. Are you encountering a glb extension issue or is it something you foresee being an issue in future?

**Comment by aidinabedi** [comment]
I see. I apparently missed that there is a new method [loadFromUrlAndFilename](https://developer.playcanvas.com/en/api/pc.AssetRegistry.html#loadFromUrlAndFilename) that can also take a filename.

Thank you @slimbuck. In that case. I'm closing the PR and issue.

**Pull request closed without merging**
