### PR TITLE
Particle with an orthographic camera fix

### PR DESCRIPTION
**Pull request by yaustar**
GitHub issue: https://github.com/playcanvas/engine/issues/893
Forum issue: http://forum.playcanvas.com/t/particle-effect-looks-different-in-orthographic/3682/3

I've taken out the billboard function into it's own fragment and depending on the projection of the camera, use the correct fragment for the billboarding transformation.

### CODE REVIEW

**Comment by Maksims** [comment]
Problem with this approach is that it will compile shader once based on camera type, but then if you change camera projection or use multiple cameras with mixed projections this approach will not work, and use one shader for both cameras.

Easiest way to preview this in this project: https://playcanvas.com/editor/scene/513932
There are two cameras, first one is Perspective and second Orthographic, because first is persp. it will compile different shader, not suitable for ortho. If you change them places, then it will be fine. But if you first have perspective camera and then set to ortho - problem again.

Editor camera preview of ortho. user cameras shows same issue.

**Comment by yaustar** [comment]
With that in mind, what is the preferable option here for the shader?
* Adding an if condition in the shader (guessing not for performance reasons)
* Using a conditional assignment operator (supposed to be better than an if?)
* Some clever math in the billboard function based on parameters passed to the shader
* Some fourth option I haven't considered?

**Comment by Maksims** [comment]
Summoning @guycalledfrank to answer those question :)

**Comment by yaustar** [comment]
Closing this PR as I made a new one due to going in a different direction with the shaders:
https://github.com/playcanvas/engine/pull/910

**Pull request closed without merging**
