### PR TITLE
Handle the ammo.js async init API introduced on April 12 2017

### PR DESCRIPTION
**Pull request by mast4461**
ammo.js changed to an async initialization API on April 12 2017 in [commit a96e001](https://github.com/kripken/ammo.js/commit/a96e001bd04dbc8965d0052869c6b903a1a2a589). This PR adapts PlayCanvas to handle that.

Anywhere that you previously did `Ammo.x` you'll have to do `Ammo().then(ammo => ammo.x)` instead. The changes to the demo files at the commit link above provide nice examples of how to migrate your code to use the new API.

If in the initialization of PlayCanvas the global initializer `Ammo` is overwritten with such a returned instance `ammo` no further edits to the PlayCanvas source code are necessary for compatibility with the async API. Furthermore, by checking whether the `then` property of `Ammo` is of type `function` the code handles versions of ammo.js without the async API as well.

The changes included in this PR could be useful for many who have struggled with using their own ammo.js builds, or newer builds released in the original ammo.js repo.

Of course, there's no guarantee that such builds would be compatible with the rest of PlayCanvas, but this PR at least provides a chance.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by c0debon** [comment]
Hi @mast4461,

Thanks for this PR.

We will actually soon be releasing an update to the editor which adds support for wasm modules. This means users will be able to provide their own version of ammo (or whatever else they require) and not be stuck with the legacy version we have provided up to now.

We are also removing the built-in version of ammo as it currently stands, so this change is probably not needed.

Thanks again for this, but hopefully what we have in the pipeline will be even better!

**Comment by mast4461** [comment]
Hi @c0debon,
Good to hear that you are working on this! Could you share anything about the time plan?
Also, will PlayCanvas be updated to be compatible with, and make use of, some current release of ammo.js?

**Comment by c0debon** [comment]
Yes we will provide the latest version of ammo with the release. I can't put definite dates on the release unfortunately, but hopefully within the next week or two.

**Comment by willeastcott** [comment]
We've deployed support for loading the latest version of Ammo now, so I'm closing this PR.

**Pull request closed without merging**
