### PR TITLE
Collision Component System update

### PR DESCRIPTION
**Pull request by LeXXik**
Updates Collision Component System to be in line with the other components.

- Moved shape implementations into own files.

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by LeXXik** [comment]
@willeastcott could you please advice on where the typescript gets duplicate declarations on the collision component from?

**Comment by Maksims** [comment]
Through engine class naming, we rarely use shortening, such as: `CollisionSystemImpl`, also, because this is not instantiated by the developer, it is worth using the full name: `CollisionSystemImplementation`.

**Comment by willeastcott** [comment]
@Maksims It was `CollisionSystemImpl` before right? This PR is just moving stuff around (plus reducing dependence on the `Data` class). I could also mention `Vec*`, `Mat*`, `Quat`. `Anim*`, etc. But yeah, as a private, internal class, I don't think it really matters too much in this instance.

**Comment by LeXXik** [comment]
@Maksims I simply kept the original name, but this could be a good time to change it.

**Comment by LeXXik** [comment]
Added a few tests for the Collision Component. There are currently 2 that are failing due to:
1. #3638
2. A compound trigger is failing to get created. Is it supported?

**Comment by yaustar** [comment]
@willeastcott Is compound collision shapes for triggers supported? 

@LeXXik Can 1. be solved by preloading the GLB container first?

**Comment by LeXXik** [comment]
Preloading it would work around the actual issue and pass the test case. I can remove the test case here, and it could be added to #3638 when a solution is found.

**Comment by yaustar** [comment]
> Preloading it would work around the actual issue and pass the test case. 

I think that would be fine for this PR

**Comment by LeXXik** [comment]
- Updated the mesh trigger test case. It was actually loading correctly, I simply didn't assign a correct render asset to the `renderAsset` field. Added an additional check on `btTriangleMesh` use.
- Removed compound trigger test case, as it is not supported by the engine at the moment.

**Comment by LeXXik** [comment]
@willeastcott could you please let me know the status of this PR review? Are there some engine features missing that you wish to see before this PR can be merged/reviewed?

**Comment by LeXXik** [comment]
Closing as not planned.

**Pull request closed without merging**
