### PR TITLE
Layers

### PR DESCRIPTION
**Pull request by guycalledfrank**
See description in https://github.com/playcanvas/engine/pull/1057

### CODE REVIEW

**Comment by willeastcott** [comment]
I've tested against the following projects and they're fine:

* [Doom3: Gangnam Style](https://playcanvas.com/project/23/overview/doom3-gangnam-style)
* [BMW i8](https://playcanvas.com/project/347824/overview/bmw-i8)
* [Creating Rigid Bodies in Code](https://playcanvas.com/project/442322/overview/creating-rigid-bodies-in-code)
* [Titanfall 2 Experience](https://playcanvas.com/project/6418/overview/titanfall-2-experience)
* [Star-Lord](https://playcanvas.com/project/333626/overview/starlord)
* [Flappy Bird](https://playcanvas.com/project/375389/overview/flappy-bird)
* [Star Wars: X-Wing](https://playcanvas.com/project/395232/overview/star-wars-xwing)
* [Steampunk Slots](https://playcanvas.com/project/482585/overview/steampunk-slots)
* [Planet Earth](https://playcanvas.com/project/419706/overview/planet-earth)
* [Warp a Sprite with GLSL](https://playcanvas.com/project/426038/overview/warp-a-sprite-with-glsl)
* [Space Base: Texture Compression](https://playcanvas.com/project/411394/overview/space-base-texture-compression)
* [Pong](https://playcanvas.com/project/851/overview/pong)
* [Call of Duty: Gunsmith](https://playcanvas.com/project/411970/overview/call-of-duty-gunsmith)
* [Sponza: Lightmap Demo](https://playcanvas.com/project/391368/overview/sponza-lightmap-demo) - works but dynamic shadows look broken for both versions of the engine
* SWERVE
* [Flying Toasters](https://playcanvas.com/project/44/overview/flying-toasters)

Problem projects:

* Virtual Voodoo - UI not visible on game start
* [This is Halloween](https://playcanvas.com/project/2361/overview/this-is-halloween)
* [Ragdoll](https://playcanvas.com/project/431888/overview/ragdoll) - camera.js calls scene.getModels() which was never public API so this is the author being 'naughty'.
* [Mixamo Characters](https://playcanvas.com/project/600/overview/mixamo-characters) - same problem as above with camera.js
* [Terminator T800](https://playcanvas.com/project/348970/overview/terminator-t800) - same problem as above with camera.js
* [WebGL Chess](https://playcanvas.com/project/428752/overview/webgl-chess) - UI not visible on game start

Questions:

* Should we make pc.Scene#getModels backwards compatible? If it's easy, probably yes. Otherwise, don't worry about it.

**Comment by yaustar** [comment]
Has this been checked against the project templates and the Ball starter project?

**Comment by willeastcott** [comment]
I have now, @yaustar. List updated.

**Comment by guycalledfrank** [comment]
- Sponza: this one is bugged simply because shadow map bias value for the dynamic spotlight is wrong. Set it to e.g. 0.5, and it's fixed. Apparently this bug appeared after we changed the way biasing works (long time ago).

- Master Archer: uses old meshInstance.layer, so this is expected. Migration to the new layer system will solve this.

- Voyager: fixed.

- UI not rendering in various projects: fixed.

- getModels() crash: fixed.

- Static Batching: can't reproduce, shows 2 to me.

**Comment by willeastcott** [comment]
Confirmed that all is fixed except the old font_renderer.js script. So I agree: let's not support that with backwards compatibility. But we _could_ just upgrade the script itself to the new layer system. So if developers do still use the script and want to get back up and running fast, they just drop in the updated font_renderer.js.

Anyway, I believe this is now good to merge. @daredevildave is coordinating this release of stuff this week, so let's just wait until he's ready.

**Comment by willeastcott** [comment]
Oh, and I still see -7 in the 'Static Batching' scene:

image

**Comment by vkalpias** [comment]
I have updated the old sprite and font_renderer scripts just haven't pushed the changes, 'cause I'm waiting for all this to be deployed first.

**Comment by willeastcott** [comment]
Yay! Nice job, @vkalpias. Looks like we're all set.

**Comment by SHADOWELITE7** [comment]
is layers like what gimp has but we are putting the feature in playcanvas

**Comment by willeastcott** [comment]
@SHADOWELITE7 There is a full description here: https://github.com/playcanvas/engine/pull/1057 (referenced at the top of this PR).

**Pull request merged**
