### PR TITLE
chore(examples): update playcanvas-spine.3.8.js

### PR DESCRIPTION
**Pull request by epreston**
update the spine plugin copied into examples to remove warnings in es5 and es6 builds.

Fixes: #5399
Supports: #5521

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Review by mvaligursky — APPROVED** [review]

**Comment by kungfooman** [comment]
Isn't it best practice to add external libraries as dependencies in `package.json`? Over time this just unnecessarily increases the repo size and `git clone` becomes slower and slower.

**Comment by mvaligursky** [comment]
I don't think we publish spine repo to npm at the moment, so this is a separate PR in the future I think.

**Comment by epreston** [comment]
> git clone becomes slower and slower.

`git clone --depth=1` is your friend.

**Comment by kungfooman** [comment]
*suddenly best practices and guidelines are not so important anymore...*

**Comment by epreston** [comment]
This file has been in the repository like this for some time.  I think the purpose of being like this is more to support the build and deployment of the examples to webservers easily.

**Comment by willeastcott** [comment]
BTW, if anyone _does_ want the Spine package published to NPM, it should be very straightforward...

**Comment by kungfooman** [comment]
The `npm build` of examples could just copy it from `node_modules` instead, doesn't make it any easier or harder... but yea, someone needs to publish it, but now it's merged anyway.

**Pull request merged**
