### PR TITLE
Support for dithering using interleaved gradient noise

### PR DESCRIPTION
**Pull request by mvaligursky**
A new type of noise, implemented without a texture lookup by directly generating the noise in the shader.

Comparison of noise patterns:
Screenshot 2024-03-15 at 11 43 49

It's a noise that's supposed to work well with TAA, as it's based on a 3x3 grid, which is what TAA typically uses for rejection.  Details: https://blog.demofox.org/2022/01/01/interleaved-gradient-noise-a-different-kind-of-low-discrepancy-sequence/

Adjusted the Dithered Transparency example to support this noise and also TAA for testing.

### CODE REVIEW

**Review by slimbuck — APPROVED** [review]

**Comment by slimbuck** [comment]
nice!

**Comment by slimbuck** [comment]
do you have any comparison screenshots old vs new?

**Comment by mvaligursky** [comment]
> do you have any comparison screenshots old vs new?

Not really, it looks about the same :(

**Comment by mvaligursky** [comment]
Or to be more specific:
- for static camera, both blue noise and IGN do great job, and TAA resolves both to almost pattern-free transparency (depending on the transparency level)
- but for moving camera, both noise types smudge the transparency about the same .. no major improvement from IGN at the moment - this is where I hoped to get an improvement, as that's where the 3x3 pixel rejection takes place.

**Pull request merged**
