### PR TITLE
_dirtifyWorld optimization

### PR DESCRIPTION
**Pull request by gameatp**
Fixes #

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
@gameatp Can you please give an explanation of this PR? Why is it safe to remove those if statements? Does this change result in a measurably faster execution of hierarchy synchronization?

**Comment by gameatp** [comment]
> @gameatp Can you please give an explanation of this PR? Why is it safe to remove those if statements? Does this change result in a measurably faster execution of hierarchy synchronization?

_Dirtifyworld is a private method, and I see only two calls:

1.

_dirtifyLocal: function () {

if (!this._dirtyLocal) {

this._dirtyLocal = true;

if (!this._dirtyWorld)

this._dirtifyWorld();

}

}

2.

_onInsertChild: function (node) {

...

node._dirtifyWorld();

}

The first two places are judged before calling, and the second place is inserted with a new node.

So I don't think it's necessary to judge the function again,It should be faster

**Comment by Maksims** [comment]
Counter in `_unfreezeParentToRoot` and `_dirtifyWorldInternal` on same test case, will show if it is called same amount of times, and there is no regressions with this PR.

And there are couple other places `_dirtyWorld` is called from. They all then have to do this check.

**Comment by gameatp** [comment]
> This change alters the behavior of the code and does not just optimizing it.
> 
> For example, previously if _dirtyWorld flag was false in _dirtifyWorld(), _dirtifyWorldInternal() would still be called which does both _dirtyNormal=true and _aabbVer++.
> 
> Same thing for the recursive call within _dirtifyWorldInternal().
> 
> Is it your intention to change this behavior?

Yes, that's a problem, too

**Comment by willeastcott** [comment]
OK, I'm going to close this since this PR is highly likely to destabilize the engine with seemingly limited performance benefit. If you feel this is unjustified, feel free to reopen.

**Pull request closed without merging**
