### PR TITLE
Small improvements to physical lights units example

### PR DESCRIPTION
**Pull request by mvaligursky**
Small updates:
- camera bit closer
- enabled area light, so the area light reflection is a rect shape
- sizes / intensities
- changed some HUD names to fit without clipping
- wider panel to fit large range of values

Screenshot 2022-09-29 at 12 07 44

### CODE REVIEW

**Review by GSterbrant — APPROVED** [review]

**Review by willeastcott — APPROVED** [review]
Nice - looks much better!

**Comment by willeastcott** [comment]
One minor point though. The UI panel labels are mostly truncated. Can we fix that perhaps?

**Comment by MAG-AdrianMeredith** [comment]
am I reading that right that the shutter speed is set to 1 second?  That seems like an odd value that would introduce a ton of motion blur if it were real

**Comment by mvaligursky** [comment]
> am I reading that right that the shutter speed is set to 1 second? That seems like an odd value that would introduce a ton of motion blur if it were real

For cameras, the units used for Shutter Speed are 1/x seconds, so in this case its 1/1000s

**Pull request merged**
