### PR TITLE
Add pc.ScriptComponent#get

### PR DESCRIPTION
**Pull request by aidinabedi**
Currently, there is no way for a TypeScript developer to properly access a script instance in a `pc.ScriptComponent`. Accessing a property with an arbitrary name on an otherwise well-defined component is not type-safe.

PR adds `pc.ScriptComponent#get` (similar to `pc.ScriptComponent#has`), to help TypeScript developers maintain type-safety (which is the primary purpose of using TypeScript).

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
Hey @Maksims - any objection to this before I merge?

**Comment by Maksims** [comment]
Would it be better to return `null` instead of `undefined` in case of no script instance?

**Comment by aidinabedi** [comment]
@Maksims Well it's a trade-off:
- `undefined` doesn't require appending `|| null` at the end of `(index && index.instance)`
- `null` is more consistent with the rest of the engine code (except `getApplication`)

I would go with `undefined` since it keeps the expression cleaner and it would have the same behavior as using JavaScript new standardized [optional-changing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) (`index?.instance`). But you decide :)

**Comment by Maksims** [comment]
I would go with consistency.

**Comment by aidinabedi** [comment]
Done

**Pull request merged**
