### PR TITLE
[FIX] Fix pc.path.extractPath for absolute path

### PR DESCRIPTION
**Pull request by velbi**
Fix code for the following reason.
```
pc.path.extractPath('path/to/file');   // returns "./path/to"
pc.path.extractPath('./path/to/file'); // returns "././path/to"
pc.path.extractPath('../path/to/file');// returns "./../path/to"
pc.path.extractPath('/path/to/file');  // returns "//path/to"
```

pr code
```
pc.path.extractPath('path/to/file');   // returns "./path/to"
pc.path.extractPath('./path/to/file'); // returns "./path/to"
pc.path.extractPath('../path/to/file');// returns "../path/to"
pc.path.extractPath('/path/to/file');  // returns "/path/to"
```

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
You changes have broken this case:

pc.path.extractPath("path/../path/to/file.txt")

It used to return:

    "./path/../path/to"

It now returns:

    "../path/to"

**Comment by velbi** [comment]
I've fixed that you said.

**Comment by willeastcott** [comment]
Excellent. Great work, @velbi !

**Comment by willeastcott** [comment]
Hey @velbi - am I right that you have not yet completed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform)? I can't find you in the responses...

**Comment by velbi** [comment]
Hi! @willeastcott - I didn't know that link.. I just submitted google docs. thanks.

**Comment by willeastcott** [comment]
Thank you!!

**Pull request merged**
