### PR TITLE
Internal function to manipulate requestAnimationFrame timestamp

### PR DESCRIPTION
**Pull request by codebon77**
Fixes #

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by codebon77** [comment]
I need functionality like this for automated visual testing. Just a suggestion, please comment!

**Comment by yaustar** [comment]
Having some form of pre or postUpdate call would be in line with initialize and postInitialize calls that we have on scripts. e.g

```
app.update(dt);
app.postUpdate(dt);
```

**Comment by daredevildave** [comment]
> Having some form of pre or postUpdate call would be in line with initialize and postInitialize calls that we have on scripts. e.g
> 
> ```
> app.update(dt);
> app.postUpdate(dt);
> ```

`app.postUpdate` already exists.

**Comment by daredevildave** [comment]
This is allocating a new object for the frame state every tick which seems unnecessary. 

Would it be better to `app._getDeltaTime(timestamp)`? Which you can patch out in your tests?

**Comment by daredevildave** [comment]
Approved, though of course we are adding a function call overhead to our main tick...

**Comment by willeastcott** [comment]
It's just called once a frame so I'm cool to merge this now.

**Pull request merged**
