### PR TITLE
Vertex maps

### PR DESCRIPTION
**Pull request by guycalledfrank**
Use vertex colors as any map (except normal and height) of phongmaterial. You can specify channels to use, as with textures. Texture maps override vertex color.

Example 1:
material.diffuseMapVertexColor = true;

Example 2:
material.glossMapVertexColor = true;
material.glossMapChannel = "r";

### CODE REVIEW

**Comment by Maksims** [comment]
Of there is a way to combine vertex color with textures and other multipliers?
Feels like they all should work together if in present instead of replacing each other.

Good example would be to have aoMap on the ground plane, and combine with ao from vertex data under trees.

**Comment by guycalledfrank** [comment]
Seems to complicated. And how are you going to blend them? It shouldn't be just multiplier. If you want to combine AO, you would usually do it with min(ao1, ao2), not multiply (overdarkening). Blending of all that things is too specialized and not straight-forward, I'd leave it for custom chunks for now.

**Comment by Maksims** [comment]
I don't see problem with multiplication at all.
There wont be over-darkening, because 0 * 0 = 0;

**Comment by guycalledfrank** [comment]
Believe me, multiplication is a shit idea.

**Pull request merged**
