### PR TITLE
Remove redundant normalisations

### PR DESCRIPTION
**Pull request by GSterbrant**
### Description

Short and simple, this accidentally made it into the #4386 PR.

### CODE REVIEW

**Review by slimbuck — APPROVED** [review]
smokin hot!

**Comment by kungfooman** [comment]
Is this really redundant or something else going on? The term redundant implies for me that the result is basically the same, but that's not what I observe when I test it:

```js
a = new pc.Vec3(10,20,30)
a.normalize()
b = new pc.Vec3(300,160,60)
b.normalize()
c = new pc.Vec3().add2(a, b)
c.normalize()
// Vec3 {x: 0.6313556044752356, y: 0.5545397420309195, z: 0.5421031038520173}
```

And removing the two normalisations:

```js
a = new pc.Vec3(10,20,30)
b = new pc.Vec3(300,160,60)
c = new pc.Vec3().add2(a, b)
c.normalize()
// Vec3 {x: 0.8387573601608582, y: 0.4870204026740467, z: 0.24351020133702336}
```

I just wonder what would be "more right".

**Comment by willeastcott** [comment]
@kungfooman In the GLSL, `dLightDirNormW` and `dViewDirW` are already normalized. In your code, `a` and `b` are not.

**Comment by kungfooman** [comment]
Thank you @willeastcott that makes sense. Just wondered if there are more such cases and found some:

https://github.com/playcanvas/engine/blob/ed0ccb055596a91f1c3e700944d1f20ebeeebed7/src/graphics/program-lib/programs/lit-shader.js#L994

https://github.com/playcanvas/engine/blob/ed0ccb055596a91f1c3e700944d1f20ebeeebed7/src/graphics/program-lib/programs/lit-shader.js#L277

And `getNormal()` seems to be always normalized: https://github.com/playcanvas/engine/blob/ed0ccb055596a91f1c3e700944d1f20ebeeebed7/src/graphics/program-lib/chunks/lit/vert/normal.js#L39

(there are four of them)

`dNormalW` seems to be always normalized:

https://github.com/playcanvas/engine/blob/ed0ccb055596a91f1c3e700944d1f20ebeeebed7/src/graphics/program-lib/chunks/lit/frag/reflDirAniso.js#L8

`dVertexNormalW` seems to be always normalized:

https://github.com/playcanvas/engine/blob/ed0ccb055596a91f1c3e700944d1f20ebeeebed7/src/graphics/program-lib/chunks/lit/frag/TBN.js#L3

https://github.com/playcanvas/engine/blob/ed0ccb055596a91f1c3e700944d1f20ebeeebed7/src/graphics/program-lib/chunks/lit/frag/TBNObjectSpace.js#L28

(not sure if its true, I am not good at GLSL, just following what makes sense to me)

**Comment by willeastcott** [comment]
@slimbuck?

**Comment by slimbuck** [comment]
`vNormalW` is an interpolant - the vertex shader sets the normal at each polygon vertex which is then interpolated across the surface of the polygon. When the fragment shader receives it (unless all 3 normals point in the same direction) the normal will no longer be length 1.0. (Which is why we renormalise it in the fragment shader).

We can likely remove the renormalization of `dVertexNormalW` in  TBN.js and TBHObjectSpace.js though, but I'll leave that for @GSterbrant to investigate.

**Pull request merged**
