### PR TITLE
Engine example using multiple cameras / viewports

### PR DESCRIPTION
**Pull request by mvaligursky**
- example showing / testing multiple viewports
- needed for testing of render-pass refactor

Screenshot 2022-06-06 at 12 44 55

### CODE REVIEW

**Comment by willeastcott** [comment]
The specular on the board surface looks a bit....flat/bright from an angle. Why is that?

**Comment by mvaligursky** [comment]
> The specular on the board surface looks a bit....flat/bright from an angle. Why is that?

I'm not entirely sure .. both IBL and directional light give us this look. It also matches pretty well with other viewers. I'd say the material properties (roughness or similar) are not set up the best for this.

**Review by willeastcott — APPROVED** [review]

**Comment by Maksims** [comment]
The environment map with a strong light source (in the texture) combined with directional light and shadows - does not go well.
To improve, reducing exposure of a cubemap - is recommended. Also matching the direction of dynamic light to the light source on a cubemap helps as well.

**Comment by willeastcott** [comment]
Whoops. I just noticed the chess board GLB is 7.6MB. We should avoid checking in such big binaries where possible to keep the clone size of the repo nice and lean.

**Pull request merged**
