### PR TITLE
Enhancement: Access to the pc.scriptType's name (with Typescript typings)

### PR DESCRIPTION
**Pull request by TheJonRobinson**
Fixes: https://github.com/playcanvas/engine/issues/2014

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
LGTM. @Maksims and @aidinabedi - did you want to comment/review before I merge?

**Comment by aidinabedi** [comment]
Checked it out. Looks good!

**Comment by willeastcott** [comment]
Sweet! Thanks for the feedback. Merging... 🎉

**Comment by TheJonRobinson** [comment]
Thanks guys! :+1:

**Pull request merged**
