### PR TITLE
Enforce single quotes and disallow `var` in unit tests

### PR DESCRIPTION
**Pull request by willeastcott**
* Enforce single quotes for all node-based unit tests (note that single quotes are used over double quotes in our codebase by over 2 to 1). I would like to see this standardized across the codebase.
* Migrate all occurrences of `var` to `let` and `const`.

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by slimbuck** [comment]
Perhaps we should standardise on ` instead?

**Comment by willeastcott** [comment]
@slimbuck That's a reasonable suggestion. However, I kind of like reserving ` for template string literals. For example, say there was a long string and I saw it started with a `, I would then have to scan the whole string to find the embedded variables which may or may not be there.

**Comment by slimbuck** [comment]
Yeah makes sense. ' is really similar to ` - perhaps " would be a better standard?

**Comment by willeastcott** [comment]
I mainly went for single because:

* It appears twice as many times in our source as double (so we'll generate fewer changes when we standardize, plus people obviously prefer single over double if that's the statistic)
* single is one keypress, double is two. :wink:

Yeah, double is visually differentiated a bit more. But does that outweigh the above? I'm not totally sold.

**Comment by slimbuck** [comment]
I would say readability of the codebase is more important than either the one-off change or double keystroke.

**Comment by slimbuck** [comment]
(and tbh I think there's a big difference in readability between " and ' vs `).

**Comment by willeastcott** [comment]
Actually, just remembered that we unofficially stick to Google's JS coding standards for the most part:

https://google.github.io/styleguide/jsguide.html#features-strings-use-single-quotes

So that's another key reason why you'll find way more singles than doubles right now. We just never enforced it.

**Comment by mvaligursky** [comment]
Personally I tend to use " for these main reasons, but no super strong preference:
- I find it easier to read, as ' vs ` is getting less obvious
- I'm used to it from c++ and c# and it feels right. My mind is wired to use ' for a single char type only
- the plugin (or built in functionality?) that VSCode has for managing imports uses " in import statements: `import { Vec3 } from "../../math/vec3.js";
`

**Comment by willeastcott** [comment]
> the plugin (or built in functionality?) that VSCode has for managing imports uses " in import statements: import { Vec3 } from "../../math/vec3.js";

If I'm following what you're talking about here, I believe VS Code is smart enough to check the quotes of other imports in the file and try to match them.

quotes

**Comment by mvaligursky** [comment]
Great! Sounds like that one is a non issue then.

**Comment by Maksims** [comment]
A single quote is easier to type, as no extra button press is required.
Template literals should be used only where it is required, linters in IDE can even highlight strings that use ` but do not utilize it with actual templating.

**Comment by willeastcott** [comment]
Haha, yeah, I can relate to that. I have a US keyboard at home and a UK keyboard in the office!

**Review by slimbuck — APPROVED** [review]
We chatted internally and decided single quote is the way to go.

**Pull request merged**
