### PR TITLE
Typedoc: assign categories to classes

### PR DESCRIPTION
**Pull request by willeastcott**
The API reference manual doesn't make any attempt to group related API into categories. Doing so enables developers to more easily find what they're looking forward if they are working in a specific area (e.g. physics, animation, graphics, etc).

So this PR updates the top-level landing page from this:

Screenshot 2023-07-22 at 09-49-11 PlayCanvas Engine API

To this:

Screenshot 2023-07-22 at 09-48-02 PlayCanvas Engine API

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by kungfooman** [comment]
Working on Saturday :see_no_evil:  That's cool, you plan to add Script / Asset category too, or would there be a minimum amount of entries to justify a new category?

**Comment by willeastcott** [comment]
@kungfooman Yeah, I love coding on the weekends! Doesn't everybody? 😎 

So good question about the scripting and asset categories. I considered it but I think anything around 5 or less classes perhaps doesn't warrant it's own category. And as for `Assets`, since most of the classes are already spread around other categories (like handlers and parsers and resources etc), I thought I'd leave that in `Others` too.

**Comment by Maksims** [comment]
Framework category could cover all Components, Entity, AssetRegistry, ScriptType and more things related to developer interacting directly from scripts.
And possibly word "Classes" is redundant in titles, as almost everything is classes.

**Comment by willeastcott** [comment]
@Maksims The word `Classes` is generated by Typedoc. It just appends the category specified in the `@category` JSDoc tag. Also, stuff does actually come after the classes - I've just cropped the screenshot below the classes sections (`Variables` and `Functions` come after).

I did also consider a `Framework` section, but unlike the other sections `Framework` is a bit more of a specific term to PlayCanvas so less obvious what it would contain. I mean, presumably `Entity` would live there, but what about `GraphNode`? And as I have it here, the different components live in each section but if `Framework` was there, should all components be listed there instead? I just thought it was slightly too nebulous to include. But I do definitely see that there's a reasonable argument for it.

**Review by slimbuck — APPROVED** [review]

**Comment by slimbuck** [comment]
<3<3<3

**Pull request merged**
