### PR TITLE
fixes animNumFrames

### PR DESCRIPTION
**Pull request by gameatp**
Fixes #1489

### CODE REVIEW

**Comment by gameatp** [comment]
The 'animNumFrames' are written as 'animFrames'

**Comment by willeastcott** [comment]
Was this causing a specific bug? Or did you just notice the code was wrong?

**Comment by gameatp** [comment]
Modifying this property of component has no effect, so I found out that the name is wrong here.

**Comment by willeastcott** [comment]
OK, great! If you fill out the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/e/1FAIpQLSfG9XHIgdapCBkvwxbXow592Y5NFPEKD5TM-TyWOmbaCbLeHA/viewform), I will merge this PR. Thanks!

**Comment by gameatp** [comment]
I Agree

**Comment by willeastcott** [comment]
Thanks! 👍

**Pull request merged**
