### PR TITLE
Migrate `framework` `scene` and `resources` folders to single quotes

### PR DESCRIPTION
**Pull request by willeastcott**
This is the second phase of migrating the engine to standardize on single quotes. This time, the folders updated are:

* `framework/components` (I left out the files in the root of `framework` because @mvaligursky has a PR open involving `AppBase`)
* `resources`
* `scene`

I suspect we'll need one or possibly two more phases to complete the switch.

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by slimbuck** [comment]
I'm wondering how you've make these changes, by hand or find/replace? There are so many changes here I can't imagine actually checking them all!

The only danger I could think of is strings with embedded ' and " characters.

**Comment by willeastcott** [comment]
@slimbuck It's 100% performed by doing:

```
npm run lint -- --fix
```

So it's reasonable to expect the transformation to be completely trusted.

**Comment by willeastcott** [comment]
BTW, I hope that you haven't been fixing lint problems by hand! You just need to run the above command and it's done for you. At least, it is for lint errors that can be auto-fixed.

**Comment by willeastcott** [comment]
Because I'm trying to avoid merge conflicts for people. For example, @mvaligursky is working in `graphics` and on the `Application` class, so just being sensitive to that.

**Review by slimbuck — APPROVED** [review]

**Pull request merged**
