### PR TITLE
Add support for torus primitive to ModelComponent

### PR DESCRIPTION
**Pull request by mast4461**
image

I noticed that there's code for [generating torus meshes](https://github.com/playcanvas/engine/blob/6923c43fc8a147b9ee5df37cda010ba3262d5db2/src/scene/procedural.js#L324), but no support for a torus primitive in [ModelComponent](https://github.com/playcanvas/engine/blob/6923c43fc8a147b9ee5df37cda010ba3262d5db2/src/framework/components/model/component.js#L12), so I attempted to add that.

However, I didn't understand how to calculate the `_area` property. Any help or hints about that would be appreciated.

~~By the way, I found it a bit confusing that the summary section of the API reference page for ModelComponent ([here](https://developer.playcanvas.com/en/api/pc.ModelComponent.html)) doesn't indicate that there are more types of primitives than the tree listed (see picture below). I assume that the summary is generated algorithmically and to avoid this problem I suggest that an [ellipsis](https://en.wikipedia.org/wiki/Ellipsis) is added at the bottom of the excerpt if there's more content than what is selected to be shown in the summary.~~ EDIT: Question [answered](https://github.com/playcanvas/engine/pull/1842#issuecomment-578702282). Problem [solved](https://github.com/playcanvas/engine/pull/1842/commits/45792472c046fd61d9d55fdbb0ad87f3770f323a).

2020-01-27 10_18_22-pc ModelComponent _ PlayCanvas API Reference

If [type](https://developer.playcanvas.com/en/api/pc.ModelComponent.html#type) is clicked the full list is shown, of course. But that's in another place.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
The way the API ref works is that there's a summary at the top and a full description further down. The summary takes the string until either the first full stop or the entire string if no full stop is found. This needs to be kept in mind when writing the @description tag because a full stop, as with this case, could appear in a floating point number, for example. Hope that explains it.

**Comment by mast4461** [comment]
@willeastcott, I understand. I rephrased the description to generate a better summary.

@guycalledfrank I searched the history and it looked like you were the one who wrote the area calculation code for the other primitives. Could you give some directions about how to derive the area calculation for the torus primitive?

**Comment by willeastcott** [comment]
I was chatting with @guycalledfrank about this on Twitter. About [this line](https://github.com/playcanvas/engine/blob/master/src/framework/components/model/component.js#L523), he said:

> I guess _area.uv is 2/3 because it was unwrapped like that, taking 2/3 of UV square (2 rows with 3 faces, one empty row). _area xyz is separated because we allow non-uniform scale. and xyz are probably each = 2 because we have 2 faces with area=1 on each side (left+right, top+bottom, front+back). so _area.xyz is the sum of projected area for each axis (including backfaces).
> 
> For a capsule, I'm not sure it looks right. I think it should be divided by 2. And even so, for side projections it won't be exactly right.

**Comment by willeastcott** [comment]
He was explaining why the box primitive is [2, 2, 2, 2/3]. I don't think he was suggesting the same values should be used by a torus.

**Comment by mast4461** [comment]
> He was explaining why the box primitive is [2, 2, 2, 2/3]. I don't think he was suggesting the same values should be used by a torus.

Oh, I see... I should have read more carefully. I'll have to do some deeper thinking on this one I guess.

**Comment by willeastcott** [comment]
Currently, app the shapes on the model component are supported by the collision component (except plane, which I guess we could actually support). The `pc.createTorus` function is there for historical reasons, but on reflection, I wouldn't mind removing the torus from the API and adding it to the new `playcanvas-extras.js` library (in the interests of keeping the core engine streamlined). I mean, there are plenty of mathematically derived meshes we could support: torus know, Utah teapot, dodecahedron, etc etc. So I think I'm against adding this to the `pc.ModelComponent` for now - so I'll close this PR. But if you strongly disagree, feel free to follow up.

**Pull request closed without merging**
