### PR TITLE
Post-effects can be applied on camera with render target

### PR DESCRIPTION
**Pull request by mvaligursky**
Note that render target cannot use antialiasing, as post-effects don't support it at the moment.

Fixes https://github.com/playcanvas/engine/issues/2941

### CODE REVIEW

**Comment by willeastcott** [comment]
I think my only concern here is that the render to texture example is being polluted a bit with another feature demonstration. Maybe if, by default, the post effect is not applied and you can enabled it by pressing a key/button. Or you can add a PCUI control like the animation examples. But devs might look at it and wonder what they're looking at because the 'TV' is now showing the same scene as  the main camera.

**Comment by willeastcott** [comment]
BTW, instead of hue-saturation, how about this kind of effect: 

https://www.shadertoy.com/view/XtK3W3

😄

**Comment by raytranuk** [comment]
>BTW, instead of hue-saturation, how about this kind of effect:

>https://www.shadertoy.com/view/XtK3W3

+1 on this - would make the example also show developers what cool possibilities using rendering to texture could have with post processes.

**Review by raytranuk — APPROVED** [review]
Code to allow post processes to render to offscreen render targets looks good - I added a comment on the changes to the engine example

**Comment by mvaligursky** [comment]
I removed changes to the example to keep it simple, and moved the example changes to separate PR to be made nicer demo of rendering to texture later.

**Review by willeastcott — APPROVED** [review]

**Comment by willeastcott** [comment]
I think that's a good decision, @mvaligursky.

**Pull request merged**
