### PR TITLE
Optimize Entity.addChild sanity check with application level index

### PR DESCRIPTION
**Pull request by daredevildave**
Possible solution for #685

### CODE REVIEW

**Comment by growf** [comment]
Certainly makes a big difference. I don't hit a wall now until ~16,000 entities and the wall I hit is somewhere in render(). Entity.addChild() has dropped from 60% of my total runtime to 7%.

**Comment by guycalledfrank** [comment]
Merge?

**Comment by Maksims** [comment]
@guycalledfrank it shall not be merged to stable, it has a bug: add/remove to index shall be applied to each child of added entity. Otherwise children wont be in index that will lead to bugs.

**Comment by daredevildave** [comment]
Actually, it's a bit more complicated than this change. I'll fix it later on with a update.

**Pull request merged**
