### PR TITLE
url encoded filename for texture access

### PR DESCRIPTION
**Pull request by sri-30**
Fixes #
Textures with hashtags in their names couldn't be accessed before due to the lack of URL encoding. This has now been fixed by encoding the filename and replacing it in the url string.

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by mvaligursky** [comment]
Strange that Karma tests are not failing locally

**Comment by yaustar** [comment]
All tests now pass :)

**Comment by willeastcott** [comment]
What was the issue that originally prompted this PR to be developed? @slimbuck - you've spent a bit of time working on image/texture loading - do you know what the deal is here? This PR's getting quite old now so it'd be cool to get a resolution one way or the other.

**Comment by willeastcott** [comment]
Since nobody seems to remember why this PR was submitted, I'm closing it...

**Pull request closed without merging**
