### PR TITLE
small reflection chunks cleanup

### PR DESCRIPTION
**Pull request by slimbuck**
Reflection chunks all pass material_reflectivity into the calcReflection() function just to have it package the value and return it to the caller. This seems unnecessary and so this PR sets the value in a more straightforward way.

@raytranuk - do you think this is an improvement? If not, I'm also happy to pull it.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
Is this change fully backwards compatible for anybody who's overridden these chunks?

**Comment by slimbuck** [comment]
It depends whether users have overridden addReflection() or calcReflection(). This change alters the signature of calcReflection(), which is a breaking change. This is a small improvement, so perhaps not worth the risk.

**Comment by willeastcott** [comment]
Well, if `addReflection` is considered "API" and `calcReflection` is internal to the chunks, the this change is fine, right?

**Comment by raytranuk** [comment]
It looks fine - for some reason I didn't notice it was just passed out again to be used at a later stage - and as Will mentioned, addReflection() is what older projects used to override.

**Comment by slimbuck** [comment]
Tested with Seemore and After the flood projects, they both seem to work fine.

**Pull request merged**
