### PR TITLE
Call preventDefault() in touchend handler

### PR DESCRIPTION
**Pull request by yayhi**
Fixes an issue whereby buttons would enter the `hover` state on mobile browsers after the `touchend` event was received, instead of going back to the `default` state. This was happening because the default behaviour of the browser is to simulate a series of `mouseenter/down/up` events immediately after the `touchend` event, in order to ensure that websites that don't explicitly listen for touch events will still work on mobile (see [here](https://www.html5rocks.com/en/mobile/touchandmouse/) for reference). Due to this, the following sequence of events is received:

```
touchstart
touchend
mouseenter
mousedown
mouseup
```

Because the `mouseenter` event is received after `touchend`, the button was entering the `hover` state. We can avoid this by only listening for mouse events when running on a desktop browser, and vice versa.

An alternative fix would be to call `event.preventDefault()` on the `touchend` event. However, as we have our [`touchend` listener marked as passive](https://github.com/playcanvas/engine/blob/master/src/input/element-input.js#L231), we're not currently able to do this. Setting passive to false is an option, but given that its intention is to improve performance (albeit largely related to scrolling performance, which perhaps doesn't apply to us so much), I figured this change would be better.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by yayhi** [comment]
Ah, interesting – great point. So perhaps we need to go with the `preventDefault()` solution I mentioned in the description? Or alternatively, perhaps we could modify `element-input.js` to provide an additional set of standardised events (i.e. called just `down`, `up` etc), which could also handle de-duplication in this scenario.

**Comment by vkalpias** [comment]
Hmmm, I'm not against either, I think it'd be better to use common browser event names but if that's going to affect performance in a way that the user can actually feel it then maybe we should do custom events.. I'd try preventDefault first personally.

**Comment by yayhi** [comment]
Updated to use `preventDefault()`. What's the best way of testing this – do we have a large/complex project we can test with?

**Comment by vkalpias** [comment]
I can't really think of a project with a lot of UI input. It should be fine mainly I think it's about whether mouse+touch enabled devices are still going to work OK. You could try something like Master Archer, I can add you if you give me your playcanvas username.

**Pull request merged**
