### PR TITLE
Make pc.SceneRegistry public

### LINKED ISSUE #1948: Make pc.SceneRegistry public
### Description

I know having more public classes is undesirable, so we wouldn't ask for this if it wasn't necessary.

Currently, there is no way for a developer to get a list of scenes, add/remove or search for one by name. This is important when a game or app needs to change or display available scenes etc.

Just like `pc.AssetRegistry`, `pc.SceneRegistry` needs to be accessible. In the future, a scene should preferably be handled like an asset - but as long as that is not the case, it makes sense to make `pc.SceneRegistry` public. It may be worth noting that [Unity's equivalent `SceneManager`](https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.html) is also available to devs for the same reason.

### PR DESCRIPTION
**Pull request by aidinabedi**
Fixes #1948

PR contains the following changes:

- Rename undocumented `pc.Application` property `_sceneRegistry` to `scenes`
(just like `pc.Application#assets` which references `pc.AssetRegistry`).
- Make `pc.SceneRegistry` and `pc.SceneRegistryItem` public.
- Add documentation for `pc.Application#scenes`.
- Add documentation  for `pc.SceneRegistryItem` properties.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by aidinabedi** [comment]
Updated PR based on [feedback from issue thread](https://github.com/playcanvas/engine/issues/1948#issuecomment-606289956):
- Mark old scene functions (in `pc.Application`) as private and deprecated (to discourage new devs).
- Add console warning (if debug build) in deprecated scene functions (to encourage switch).

**Comment by willeastcott** [comment]
Hey @vkalpias - I think your review is probably the most authoritative here. The one thing I'm thinking is that we'd have to update and deploy the Editor at the same time as this PR. Because we would want exported apps to use the functions on the `pc.SceneRegistry` instead of `pc.Application`. That said, exported apps use the release engine so no console warnings will appear.

**Comment by vkalpias** [comment]
> Hey @vkalpias - I think your review is probably the most authoritative here. The one thing I'm thinking is that we'd have to update and deploy the Editor at the same time as this PR. Because we would want exported apps to use the functions on the `pc.SceneRegistry` instead of `pc.Application`. That said, exported apps use the release engine so no console warnings will appear.

Well this only seems to change the internal `_sceneRegistry` to `scenes`. Don't see any other changes that would affect the Editor.

**Comment by vkalpias** [comment]
Oh I see what you mean - all the new Deprecated messages. Yeah not sure we need those can't we just keep the old functions without deprecating them?

**Comment by willeastcott** [comment]
No, because they're duplicates and it makes for an ugly API. 😁  Like I say, I don't actually think it's a big deal because you can't publish with the debug engine. But we should, for correctness, update the generated app to use the new API.

**Pull request merged**
