### PR TITLE
Fix regression of world space drag bug #3748 

### PR DESCRIPTION
**Pull request by yaustar**
Fixes https://github.com/playcanvas/engine/issues/3748

PR https://github.com/playcanvas/engine/pull/4935 reintroduces the bug #3748

This PR zeros out the local Z translation of the drag in `_screenToLocal` so that the element can only move along it's local Y and X axis

1.59

https://user-images.githubusercontent.com/16639049/208466764-9a696a48-025e-40d8-94ef-fb0a17cebd34.mp4

With this PR and #4935

https://user-images.githubusercontent.com/16639049/208466741-67a52e15-fb32-43cc-8a56-8a7a72388750.mp4

CC @kungfooman 

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Review by willeastcott — APPROVED** [review]
Approving but get @kungfooman's approval too! 😄

**Comment by kungfooman** [comment]
Wow, thank you for fixing this so quickly!

I would love to properly test it, but it takes some time and I'm in the process of finishing something else rn, so I could do it tomorrow

**Comment by yaustar** [comment]
Yeah, tomorrow or later this week is fine :)

**Comment by kungfooman** [comment]
I tested this in different circumstances and it works perfectly, great job :+1:

**Pull request merged**
