### PR TITLE
AssetRegistry will now throw error if an duplicate id/url is added

### PR DESCRIPTION
**Pull request by daredevildave**

### CODE REVIEW

**Comment by willeastcott** [comment]
@daredevildave Can we reach a final decision on what to do with this one, please? 😄

**Comment by willeastcott** [comment]
@vkalpias I suggest we close this. I have never personally seen a bug happen as a result of multiple assets having the same id/url.

**Comment by vkalpias** [comment]
> @vkalpias I suggest we close this. I have never personally seen a bug happen as a result of multiple assets having the same id/url. If nobody has merged this after a year and a half, it can't be that important. 😄

👍

**Comment by willeastcott** [comment]
OK, closing. Thanks for taking a look. 😄

**Pull request closed without merging**
