### PR TITLE
Adding rollup replace

### PR DESCRIPTION
**Pull request by marklundin**
This PR covers an edge-case when using 'use_local_engine' during development with Script ES Modules. 

In this scenario the engine is running on 'localhost:51000' meaning that any modules imported via the engine are relative to localhost and not the document. This means that user ESM Scripts are incorrectly imported from localhost.

Rather than introducing any logic into the engine itself (this is only applies for local dev) or pointing to window.location. This PR simply allows us to replace symbols and inject the host url during development via 
```
ASSET_BASE_URL=https://launch.local-playcanvas.com/ && npm run watch
```
At final build, this will have no change on the build output.

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Review by isumygin-sc — APPROVED** [review]

**Comment by isumygin-sc** [comment]
tests are broken for some reason

**Comment by kungfooman** [comment]
Tests should work after committing `package-lock.json`

**Comment by slimbuck** [comment]
We're already using jscc for text replacement in the rollup build. Could you use that instead?

**Comment by kungfooman** [comment]
I have a feeling that `jscc` would even replace assignments, e.g.

```js
const ASSET_BASE_URL = '';`
```

would turn into:

```js
const https://launch.local-playcanvas.com/ = '';
```

(kinda low-level C preprocessor)

**Comment by marklundin** [comment]
OK closing this 👍 jscc covers this usecase

**Pull request closed without merging**
