### PR TITLE
Removed 'if not null' documentation as it cannot be null in Particle Component

### PR DESCRIPTION
**Pull request by yaustar**
Fixes https://github.com/playcanvas/developer.playcanvas.com/issues/238

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
Wait, are you saying that if I add a `particlesystem` component to an entity and I set `localVelocityGraph`, and then query `localVelocityGraph2`, does it return `localVelocityGraph` or `null`...or something else? This is a bit confusing.

**Comment by yaustar** [comment]
Here is the original thread: https://forum.playcanvas.com/t/change-local-velocity-of-particle-system/17961/

The current documentation implies that localVelocityGraph2 was optional but it isn't the case. Both localVelocityGraph and localVelocityGraph2 need to be set for a particle system to behave correctly.

In the Editor, if randomise is unticked for the graph, it will set both localVelocityGraph and localVelocityGraph2 to be the same graph.

**Comment by mvaligursky** [comment]
I looked at engine example particles-snow, and when I comment out these two lines:

```
                velocityGraph2: velocityCurve2,
                rotationSpeedGraph2: rotCurve2,
```

the example still runs, but the randomisation is gone. That suggests that these parameters can be null.

**Comment by yaustar** [comment]
Doesn't seem to work when velocityGraph2 is explicitly set to null after creation though: https://playcanvas.com/editor/scene/1093460

```
var ParticleVelocity = pc.createScript('particleVelocity');

ParticleVelocity.prototype.initialize = function() {
    var self = this;
    setTimeout(function() {
        console.log(self.entity.particlesystem.localVelocityGraph);
        self.entity.particlesystem.localVelocityGraph = new pc.CurveSet([

            [0, 0],


            [0, 0],


            [0, 0]

        ]);
        
        self.entity.particlesystem.localVelocityGraph2 = null;
        
        self.entity.particlesystem.reset();
        console.log(self.entity.particlesystem.localVelocityGraph);
    }, 1000);
};

```

**Comment by mvaligursky** [comment]
We need to check if this is a bug or expected behaviour.

**Pull request closed without merging**
