### PR TITLE
RFC: Refactor/context-components

### PR DESCRIPTION
**Pull request by daredevildave**
This PR does two things:
- Removes `pc.ApplicationContext` and replaces it everywhere with `pc.Application`
- Adds `pc.Entity#addComponent` and adds an optional argument `new pc.Entity(app)` to the Entity, to set the currently used application.

The change is backwards compatible for online projects by using the default Application if no argument is passed to Entity.

See `examples/load_model/index.html` and `examples/animation/index.html` for an overview of how the new API looks compared to before.

Comments in particular about new Entity/addComponent API welcome.

### CODE REVIEW

**Comment by Maksims** [comment]
As we have (assumption) only rare cases of multiple Applications per page, then whole work with App is more edge case rather than a norm, so we potentially have to move away the need to worry about providing App for majority users, and keep ability for edge cases.
That is possible by creating one global variable `currentApp` that will be set to app on: create new app, call app.update, and few other situations. Then when you create an Entity, if `app` is not provided, it uses `currentApp`, which in majority (99% cases, assumption) will be what you want.

That is little 'magic' behind the scenes, but it is great benefit for most users. Then we just clearly say: if you want multiple Applications per web page, then make sure you provide `app` when you create Entity, that's it.

So that way we are looking at: `new pc.Entity();` as a holy grail.
Some example what I think looks good:

```javascript
var app = new pc.Application(canvas);

// ...

var light = new pc.Entity();
light.translate(5, 0, 15);

var point = light.addComponent("light");
point.type = "point";
point.color = new pc.Color(1, 1, 1);
point.range = 100;

app.root.addChild(light);
```

**Comment by guycalledfrank** [comment]
Maksims, that would be much better :)

**Comment by willeastcott** [comment]
I'm not keen on that. There shouldn't be two ways of doing things. "Pass this parameter if you think you might run your app on the same page as another app even though you might not know at the time. And if you don't pass the parameter, and your app does at some point run alongside another, the results will be undefined." That's bad API design IMHO.

I personally like:

  var light = scene.createEntity().addComponent('light');

@daredevildave points out to me that createThing is not a paradigm we use much in the engine which is a very valid observation. But maybe we should? This means developers can move away from calling 'new' and we can start using smarter allocation schemes internally.

I do concede that @Maksims suggestion is quick and easy to implement and is generally an improvement though - so a compromise. But it doesn't mean I like it. ;)

**Comment by vkalpias** [comment]
If we had scene.createEntity then typically users would write this in their
scripts:

context.scene.createEntity();

vs

new pc.Entity(app);

**Comment by vkalpias** [comment]
Unless context is removed now? I'm confused

**Comment by daredevildave** [comment]
In this PR context is replaced with app, but principle remains:

`app.scene.createEntity()`

Unless we provided additional argument to script callback to provide the scene as well.

**Comment by Maksims** [comment]
`app.scene.createEntity()`
vs
`new pc.Entity()`

**Comment by daredevildave** [comment]
Pinging everyone again on this:

Current status is:

    var entity = new pc.Entity(); // optional `app` argument, use default "current" application if not provided
    entity.addComponent("light", {
        type: "directional",
        color: new pc.Color(1,0,0)
    });
    app.root.addChild(entity);

This shouldn't break any existing projects. I'd like to merge this if there are no more objections.

**Comment by vkalpias** [comment]
I'm fine with it.

**Comment by Maksims** [comment]
That is huge improvement.
Can we update README too?

**Comment by daredevildave** [comment]
Assuming approval I will update readme and examples.

**Pull request merged**
