### PR TITLE
Vec and Quat source args

### PR DESCRIPTION
**Pull request by slimbuck**
Follow up PR to #5567 to allow specifying source on Vec2, Vec3, Vec4 and Quat operations.

### CODE REVIEW

**Comment by willeastcott** [comment]
Anything to do for `Color`?

**Comment by kungfooman** [comment]
Is the main goal to reduce amount of code we have to write or make things faster (or both)?

Like usually we would do: `mat.copy(otherMat).invert()`
And now we just do: `mat.invert(otherMat)`?

Is this making calculations faster, because we can get rid of .copy (benchmark would be interesting) or what is the philosophy behind these changes?

**Comment by slimbuck** [comment]
These changes bring a little consistency with existing functions like lerp, add, cross, etc which already fill `this`. In some cases as you say, it'll negate the need for an additional copy and also make calling code a little more succinct. I see this change as adding some expressive power to the math API without breaking backwards compatibility.

And for me personally, I like the mental model that `this` is the target storage for math operations.

**Comment by slimbuck** [comment]
> Anything to do for `Color`?

Don't see anything.

**Review by willeastcott — APPROVED** [review]

**Comment by LeXXik** [comment]
Those look like static methods to me. I feel like if I'd want to change `this` storage I should be doing something like `pc.Mat4.invert(other)`, rather than using one random instance to change another.

**Pull request merged**
