### PR TITLE
Layer.cullingMask and Camera.cullingMask has been removed as not needed

### PR DESCRIPTION
**Pull request by mvaligursky**
Obsolete functionality no longer used.

### CODE REVIEW

**Review by willeastcott — APPROVED** [review]
Seems safe enough to me. Even if somebody uses this API, they app should still run, as far as I can tell.

**Comment by LeXXik** [comment]
What would be the right way to migrate an old project that used that functionality? For example:
https://playcanvas.com/project/668042/overview/my-toon-water

**Comment by mvaligursky** [comment]
The Layers need to be used instead. Culling mask is basically like a list of Layers - each bit represents a Layer.

**Comment by MAG-AdrianMeredith** [comment]
This was really handy, definitely not obsolete.  

It allowed us to remove certain meshes from a layer just for a draw call.  True we could have created a bunch of different layers but this seems a more elegant way to do it. 
Is this documentation no longer correct? 
"Mask controlling which LightComponents light this mesh instance, which **CameraComponent** sees it and in which Layer it is rendered."

**Comment by mvaligursky** [comment]
It was a left over from the system before the layers were implemented. I agree the Layers are little bit heavy, and I wish under the hood they used bitflags, but they don't.

I think we've yet to release the docs for the engine, which should take place shortly. Sorry about that.

**Pull request merged**
