### PR TITLE
[JSDOC] Improve ScriptType documentation

### PR DESCRIPTION
**Pull request by aidinabedi**
PR includes the following JSDoc changes for ScriptType:
- Improve types for constructor parameters `args.app` and `args.entity`
- Change return type for `pc.createScript` from `Function` to `pc.ScriptType`
- Add optional overridable methods `initialize`,  `postInitialize`,  `update`,  `postUpdate`,   `swap`
- Add `ScriptType` as additional possible type for parameter `name` in `pc.ScriptComponent#create`
- Add prefix `pc.` to ScriptType so that the TypeScript declaration is also available in the npm package ([only declarations in namespace `pc` are actually exported](https://github.com/playcanvas/engine/blob/master/index.d.ts#L3) since that is what [the built code exports](https://github.com/playcanvas/engine/blob/master/build/umd-wrapper.js#L5))

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
Hey @Maksims - was there a reason you didn't put ScriptType in the pc namespace? Do you have any comments on this PR?

**Comment by aidinabedi** [comment]
@Maksims probably has a better answer but I suspect the reasoning might have been that the "implementation" of `ScriptType` isn't actually exposed (it's "hidden" [inside `pc.createScript`](https://github.com/playcanvas/engine/blob/master/src/script/script.js#L298)). `ScriptType` is [only documented](https://developer.playcanvas.com/en/api/ScriptType.html) to seem like a global type.

However, this is also something I would like to change in an upcoming PR. Since our devs (and I suspect many others) prefer reading & writing [ES6 classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) (also used in TypeScript) rather than [ES5-type classes](https://www.accelebrate.com/blog/javascript-es6-classes-and-prototype-inheritance-part-1-of-2/). So that script can **optionally** be defined like this:
```javascript
class CameraController extends pc.ScriptType {

    initialize() {
        // initialize code called once per entity 
    }

    update(dt) {
        // update code called every frame
    }
}
```

We actually already implemented this in an older PlayCanvas and it works without issue. You just need one line of code that registers the script like so `registerScript(CameraController)` (the script name will be the same as the class).

Similar to TypeScript, ES6 code can easily be transpiled to vanilla ES5 so browser support is not an issue either. And the biggest benefit of ES6+ code is that ES6 modules/classes that aren't actually used by your application code are automatically stripped when transpiled, thus decreasing the download and load time.

**Comment by Maksims** [comment]
Hi @aidinabedi. Technically "ScriptType" as a type, does not exists. There is no function/class called ScriptType. It is an abstraction. `createScript` creates new function every time and returns it, for developer to extend and implement own prototype functions and properties with attributes on top of it. `ScriptType` exists in docs, just for convenience for a reader, as well as for autocomplete to work well in online IDE.

So trying to give namespace to it, is to pretend it actually is a function. But then developers will be confused, why `pc.ScriptType === undefined`.

There should be a better way to improve TypeScript bindings for it, without affecting vanilla code.

**Comment by aidinabedi** [comment]
@Maksims I think you misinterpreted by previous comment.

I know `ScriptType` "technically" doesn't exist in the `pc` namespace. I also know it's a class created inside `createScript`. Hence why I referred to the implementation as "hidden".

I agree that `pc.ScriptType === undefined` is not perfect but there are other types that are similar ([like the type definitions in `pc.callbacks`](https://developer.playcanvas.com/en/api/pc.callbacks.html)). Additionally, the code could have a dummy implementation in the code like so:
```javascript
var createScriptError = function () {
    new Error("ScriptType must be created using pc.createScript");
};

pc.ScriptType = createScriptError;
pc.ScriptType.attributes = {
    add: createScriptError,
    get: createScriptError,
    has: createScriptError,
    remove: createScriptError
};
```

The problem I would like to solve is that the documentation is not really in sync with the JS implementation. It gives the illusion of a type called `ScriptType` in the global namespace (rather than in `pc`). And since the docs are the only source from which TypeScript declarations are generated, developers will currently be confused either when using the declarations or interpreting the docs literally.

I argue that this PR (together with a dummy implementation) is the most sensible solution while minimizing the amount of changes in a single PR. After that I would like to finish an implementation (in an upcoming PR) where `ScriptType` is actually usable like a regular class (as hinted in my previous comment) while maintaining backwards-compatibility.

**Comment by willeastcott** [comment]
My personal feeling is that any confusion can be cleared up in the docs.

> There should be a better way to improve TypeScript bindings for it, without affecting vanilla code.

Unless you have any specific suggestions, I think we should just merge this.

**Pull request merged**
