### PR TITLE
Added public API for Container resource

### PR DESCRIPTION
**Pull request by yaustar**
JS docs for the properties of a container resource

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by mvaligursky** [comment]
Maybe we should hold off exposing model api, the others are fine. With the changes to render component, we have new API to create entity with model, or entity with render on it.

**Comment by yaustar** [comment]
Ah, there's interesting to hear that the API might change.

**Comment by yaustar** [comment]
Removed model

**Comment by mvaligursky** [comment]
it might not change (and likely will not), but we might not make it public and only expose the new api

**Review by mvaligursky — APPROVED** [review]

**Review by willeastcott — APPROVED** [review]

**Pull request merged**
