### PR TITLE
Example for rendering to texture with postprocessing

### PR DESCRIPTION
**Pull request by mvaligursky**
-temp example changes to make into something nicer

related to https://github.com/playcanvas/engine/pull/3069

Screen Shot 2021-04-07 at 5 49 36 PM

### CODE REVIEW

**Comment by willeastcott** [comment]
Any plans for this PR, @mvaligursky?

**Comment by mvaligursky** [comment]
yeah now that the example browser is ready, I'll see what's the best way to showcase this.

**Comment by marcusx2** [comment]
Where's the example scene for this?

**Comment by mvaligursky** [comment]
> Where's the example scene for this?

It's created programatically. This example is based on this: https://playcanvas.github.io/#/graphics/render-to-texture
Just adds postprocessing on the rendered texture.

**Comment by mvaligursky** [comment]
I'll just close this for now, nothing special about it.

**Pull request closed without merging**
