### PR TITLE
Handle missing bones of skeletal animations more gracefully

### LINKED ISSUE #850: Skeleton Animations to handle missing bones more gracefully
In relation to this forum thread: http://forum.playcanvas.com/t/solved-error-after-make-an-add-to-the-code/3385/8

https://github.com/playcanvas/engine/blob/master/src/anim/skeleton.js#L70

If the bone is missing, `interpKey` is undefined and leads to an uncaught exception. We should check if the bones exists and tell the developer in debug if they don't?

### PR DESCRIPTION
**Pull request by stefnotch**
Fixes https://github.com/playcanvas/engine/issues/850

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
This looks good - thanks! 👍 

Are you sure you signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/e/1FAIpQLSfG9XHIgdapCBkvwxbXow592Y5NFPEKD5TM-TyWOmbaCbLeHA/viewform)? I can't find your GitHub username...

**Comment by stefnotch** [comment]
Oh, I probably messed up when submitting the CLA. I resubmitted it. (Though, really, my phone number? That's absolutely private information.)

**Comment by willeastcott** [comment]
Hmm, well, you can be assured that your phone number is kept completely confidential. The spreadsheet to which contributor details is recorded to has never actually been used (and may never be), but we record this info anyway. It would certainly never, under any circumstances, be shared with a third party!

(To be honest, you could put in a fake number and it wouldn't make a difference. I guess it's more in your interest that it's accurate in case something potentially in your interest requires us to contact you in the future about your contributions).

**Comment by willeastcott** [comment]
And thanks for this fix, BTW! It's been bugging me for a long time, so it's much appreciated!

**Comment by stefnotch** [comment]
@willeastcott Great to hear that my information will be kept safe! Also, thank you for so quickly responding to my PR and merging it; this issue was bugging me as well.

**Pull request merged**
